### ISSUE TITLE
No such file or directory: 'pdftoppm'

### ISSUE THREAD

**Issue by Scott-Snapdocs** [Belval/pdf2image#1]
Running through the example:
```
from pdf2image import convert_from_path
images = convert_from_path('PDFs/2625605.pdf')
```

Raises the error `FileNotFoundError: [Errno 2] No such file or directory: 'pdftoppm'`

I'm running on Mac, is there anything else I need to have installed?

**Comment by Belval** [comment]
You have to install `poppler` using `brew`.
[See here](http://macappstore.org/poppler/)

**Comment by Belval** [comment]
Updated the README.md, please tell me if you have trouble installing poppler.

**Comment by Scott-Snapdocs** [comment]
Perfect thanks! 

I'm also new to PIL, but it looks like I need
```from PIL import Image``` to save as well.

**Comment by Belval** [comment]
You do need PIL. It might be counter-intuitive but you install it by running `pip3 install pillow`.
