### ISSUE TITLE
Version 0.1.9 doesn't include latest modifications

### ISSUE THREAD

**Issue by maephisto666** [Belval/pdf2image#10]
Hi @Belval ,

I was the one asking for a modification some days ago (https://github.com/Belval/pdf2image/issues/9).

Your latest modification is 3 days ago, but version 0.1.9 has been released 20/3/2018, so in the latest version your latest modifcations are not included.

**Comment by Belval** [comment]
Thanks for reminding me!

https://pypi.python.org/pypi/pdf2image/0.1.10
