### ISSUE TITLE
cap the number of pages to convert to image in `convert_from_path`

### ISSUE THREAD

**Issue by joaomicunha** [Belval/pdf2image#100]
Is there a way to cap the number of pages to convert to image ? i.e. if we have a pdf with 90 pages and only want to convert the first 3 to image. 

If not, would be easy to add?

Many thanks

**Comment by Belval** [comment]
Hi,

To only process page 1 to 3, use `last_page=3`

See https://pdf2image.readthedocs.io/en/latest/reference.html#functions

**Comment by joaomicunha** [comment]
thanks a lot missed this :/
