### ISSUE TITLE
convert_from_path not working

### ISSUE THREAD

**Issue by cher1998** [Belval/pdf2image#102]
When used convert_from_path the exception file couldn't be found is raised.
`AttributeError                            Traceback (most recent call last)
~\AppData\Local\Continuum\anaconda3\lib\site-packages\pdf2image\pdf2image.py in _page_count(pdf_path, userpw, poppler_path)
    359         # This will throw if we are unable to get page count
--> 360         return int(re.search(r"Pages:\s+(\d+)", out.decode("utf8", "ignore")).group(1))
    361     except:

AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

PDFPageCountError                         Traceback (most recent call last)
<ipython-input-3-113f067b0b98> in <module>
      1 for file in os.listdir('../Bi2i-FinanceDocs/')[:2]:
      2     if '.pdf' in file:
----> 3         pages = convert_from_path(file, 300)
      4         print(len(pages))

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pdf2image\pdf2image.py in convert_from_path(pdf_path, dpi, output_folder, first_page, last_page, fmt, thread_count, userpw, use_cropbox, strict, transparent, single_file, output_file, poppler_path, grayscale, size)
     78         poppler_path = poppler_path.as_posix()
     79 
---> 80     page_count = _page_count(pdf_path, userpw, poppler_path=poppler_path)
     81 
     82     # We start by getting the output format, the buffer processing function and if we need pdftocairo

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pdf2image\pdf2image.py in _page_count(pdf_path, userpw, poppler_path)
    361     except:
    362         raise PDFPageCountError(
--> 363             "Unable to get page count. %s" % err.decode("utf8", "ignore")
    364         )
    365 

PDFPageCountError: Unable to get page count. I/O Error: Couldn't open file 'example.pdf': No error.

`

Installed the poppler binaries and added to path variables 
tried pdfinfo in cmd its working..

**Comment by Belval** [comment]
This part of the trace: ` Unable to get page count. I/O Error: Couldn't open file 'example.pdf': No error.` seems to indicate that it is unable to read the pdf that you are trying to convert.

Try using `convert_from_bytes(open('your_path/example.pdf').read())` and see if it is able to read the file.

**Comment by cher1998** [comment]
Don't Know the reason but convert_from_bytes worked.
Thank You
