### ISSUE TITLE
Provide the _page_count interface?

### ISSUE THREAD

**Issue by NullYing** [Belval/pdf2image#105]
In some cases, we need to get the page number of pdf.

```python
from pdf2image.pdf2image import _page_count

_page_count(pdf_path)
```

**Comment by Belval** [comment]
Indeed, I feel like this is a valid usecase, do you think all the information from `pdfinfo` could be useful? I could create somekind of pdfinfo object that would contained page_count, but also author, which standard was used, etc...

**Comment by NullYing** [comment]
> Indeed, I feel like this is a valid usecase, do you think all the information from `pdfinfo` could be useful? I could create somekind of pdfinfo object that would contained page_count, but also author, which standard was used, etc...

Great, it's necessary
