### ISSUE TITLE
pdf2image cannot import convert_to_path()

### ISSUE THREAD

**Issue by jeromemassot** [Belval/pdf2image#110]
**Describe the bug**
After installing poppler and pdf2image on my Win10 system in a conda env, I have the following error : 

**from pdf2image import convert_from_path
ImportError: cannot import name 'convert_from_path'**

I have read that the path to the poppler bin directory has to be provided. It is quite difficult when you are inside a conda env to reach the environment variables, so I was happy to see the parameter poppler_path in the convert_from_path method.

first_page = convert_from_path(
            file, 
            output_folder=output_path, 
            last_page=0, 
            first_page=0,
            size=(400,None),
            poppler_path='C:\\program files\\poppler\\bin'
            )
But it cannot find the convert_from_path neither

Is it a bug ?
Or can someone already had pdf2image working in Win10 through a conda env?

Thanks

Jerome

**Comment by Belval** [comment]
Not sure what the origin of your problem is, but it is not related to poppler, you should be able to import convert_from_path with any issue.

Could you run in an interpreter:

>>> import pdf2image
>>> dir(pdf2image)


And tell me the output?

**Comment by jeromemassot** [comment]
Hi Belval,
thanks for your answer. I have just noticed that I have call my file pdf2image.py... so of course it did work correctly ...
The issue report can be closed I guess
Best regards

Jerome

**Comment by philosophy365** [comment]
glad when I googled “pdf2image cannot import convert_from_path” this came up on the top. I made the same mistake lol.

**Comment by hfy-swu** [comment]
I also have call my file pdf2image.py...same mistake ... QAQ
