### ISSUE TITLE
input kwargs for convert_from_path incorrect

### ISSUE THREAD

**Issue by baj1210** [Belval/pdf2image#111]
**Describe the bug**
size, and single_page input arguments for convert_from_path incorrect, possibly more - those are the two I got errors on.

**To Reproduce**
from pdf2image import convert_from_path
path='here.pdf'
pages = convert_from_path(path,  size=(100,100),  fmt = 'png')

TypeError: convert_from_path() got an unexpected keyword argument 'size'
Same error for single_page keyword

**Desktop (please complete the following information):**
 - Ubuntu Bionic, Python 3.6

**Comment by Belval** [comment]
What version of pdf2image are you using?

**Comment by baj1210** [comment]
pdf2image==1.5.4

I installed with pip

**Comment by baj1210** [comment]
pdf2image==1.5.4

I installed with pip

**Comment by baj1210** [comment]
Reopened since I accidentally closed it due to rogue mouseclick

**Comment by Belval** [comment]
Version 1.9.0 is the one with the `size=(X,Y)` parameter. I would suggest that you update your version to 1.10.0.

I noticed that the documentation did not include that information, I will fix that.

**Comment by baj1210** [comment]
I pulled the latest version from pip. It looks like I had installed it with anaconda (not pip) so it was a much earlier version. Thank you
