### ISSUE TITLE
Doubt on resolution

### ISSUE THREAD

**Issue by ricardobarroslourenco** [Belval/pdf2image#115]
I have a general doubt on the `convert_from_bytes` method. The `dpi` parameter is set as [default](https://github.com/Belval/pdf2image/blob/dbca3e887984ef941b98a2e2efeafa584e619838/pdf2image/pdf2image.py#L203) to 200.

How does this aspect of dpi works? Does it perform interpolation when the set dpi is different from the document source?

**Comment by Belval** [comment]
It's a good question, I believe it is simply upsampling the image.

You can see the official source for more details, as this is only a wrapper: https://gitlab.freedesktop.org/poppler/poppler

I will look on my side, but I doubt that it is much more complicated than dpi = dot per inches, the PDF has a page format in inches as well so `resolution = format * dpi` + bilinear upsampling.

**Comment by Belval** [comment]
I have been working with PDFs a lot more lately so I feel like I can answer this question better.

The DPI setting is indeed the pixel density that will be used when doing the rasterization of the document. It does not perform any interpolation directly as the content of the PDF is defined as paths that can be scaled normally (aka not "guessing" what it should look like). As such, a PDF document source will not have an hardcoded dpi settings. You can use `dpi=600` and the output image will simply be huge without any loss of quality.

That being said, it does not apply to images that could be embedded in the PDF itself. Those will be resized with a regular interpolation algorithm.
