### ISSUE TITLE
Convert 'ABC.pdf' to 'ABC.jpg'

### ISSUE THREAD

**Issue by xxxpsyduck** [Belval/pdf2image#119]
Hello. Currently the module outputs an image with random name when using 'output_folder' option. Can you change this so the output image has same name as the input pdf?

**Comment by Belval** [comment]
You can get that by using `single_file=True` when calling pdf2image.

**Comment by xxxpsyduck** [comment]
In face, I use the following command: 
`images = convert_from_path(pdf_path='ABC.pdf', dpi=300, output_folder='outputs/', fmt='JPEG',single_file=True, paths_only=True)` 
The output image's name is "63315682-c553-4bd5-a9c0-53a2fdb53f89.jpg"

**Comment by Belval** [comment]
I was able to reproduce on my side, I will fix it and release a new version.

**Comment by Belval** [comment]
Wait I was wrong (happens with more obscure feature like that), if you want a matching name, you have to use the `output_file` option with `single_file`.

For example here:

`images = convert_from_path(pdf_path='ABC.pdf', dpi=300, output_folder='outputs/', fmt='JPEG',single_file=True, paths_only=True)`

`images = convert_from_path(pdf_path='ABC.pdf', dpi=300, output_folder='outputs/', fmt='JPEG',single_file=True, paths_only=True, output_file='ABC')`
