### ISSUE TITLE
pdf2image.exceptions.PDFPageCountError: Unable to get page count.

### ISSUE THREAD

**Issue by Syncriix** [Belval/pdf2image#120]
Hey devs! Hope you had a good start in to the new year!
I have hit a bump, if I run the following code:
```python
convertedpdf = pdf2image.convert_from_path(file, #Use the file attached to the git issue
                                           dpi=200,
                                           grayscale=False,
                                           poppler_path="C:/bin/",
                                           output_folder=savepath, #wherever
                                           fmt='jpg')
```
I get the error:

```txt
2020-01-04 21:32:36,200 [JobCreator] [runtime] [ERROR]
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\pdf2image\pdf2image.py", line 419, in pdfinfo_from_path
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\X\source\repos\X\JobCreator.py", line 563, in ConvertPdfToJpg
    fmt='jpg')
  File "C:\Python37\lib\site-packages\pdf2image\pdf2image.py", line 90, in convert_from_path
    page_count = pdfinfo_from_path(pdf_path, userpw, poppler_path=poppler_path)["Pages"]
  File "C:\Python37\lib\site-packages\pdf2image\pdf2image.py", line 429, in pdfinfo_from_path
    "Unable to get page count.\n%s" % err.decode("utf8", "ignore")
pdf2image.exceptions.PDFPageCountError: Unable to get page count.
pdfinfo version 0.68.0
Copyright 2005-2018 The Poppler Developers - http://poppler.freedesktop.org
Copyright 1996-2011 Glyph & Cog, LLC
Usage: pdfinfo [options] <PDF-file>
  -f <int>             : first page to convert
  -l <int>             : last page to convert
  -box                 : print the page bounding boxes
  -meta                : print the document metadata (XML)
  -js                  : print all JavaScript in the PDF
  -struct              : print the logical document structure (for tagged files)
  -struct-text         : print text contents along with document structure (for tagged files)
  -isodates            : print the dates in ISO-8601 format
  -rawdates            : print the undecoded date strings directly from the PDF file
  -dests               : print all named destinations in the PDF
  -enc <string>        : output text encoding name
  -listenc             : list available encodings
  -opw <string>        : owner password (for encrypted files)
  -upw <string>        : user password (for encrypted files)
  -v                   : print copyright and version info
  -h                   : print usage information
  -help                : print usage information
  --help               : print usage information
  -?                   : print usage information

```

Referencing #48, I have popler installed, pdfinfo is in my path - and if called on the attached pdf it works flawlessly. The code works just fine with pdf's from other sources

[foot reflexology chart 02.jpg.pdf](https://github.com/Belval/pdf2image/files/4022425/foot.reflexology.chart.02.jpg.pdf)

OS: Win 10 up to date
pdf2image: 1.11.0
pdfinfo and poppler: 0.68.0

**Comment by Belval** [comment]
Conversion worked on my Ubuntu 18.04 machine with pdf2image 1.11.0 so the problem comes from the executable (maybe pdf2image truly doesn't have access to pdfinfo) or from some encoding/locale problem.

Could you run pdfinfo.exe on your pdf on your machine and paste the results?

**Comment by Syncriix** [comment]
I did specify 
```python
# -*- coding: utf-8 -*-
```
maybe that is the cultpit?
and the output of pdfinfo is:
```
Title:          TITLE
Subject:        Subject
Keywords:       Keywords
Author:         Author
Creator:
Producer:       https://www.convertapi.com
CreationDate:   01/04/20 21:32:35 W. Europe Standard Time
ModDate:        01/04/20 21:32:36 W. Europe Standard Time
Tagged:         no
UserProperties: no
Suspects:       no
Form:           none
JavaScript:     no
Pages:          1
Encrypted:      no
Page size:      587 x 845 pts
Page rot:       0
File size:      112103 bytes
Optimized:      no
PDF version:    1.7
```
Going to try and mess around with the perms now

**Comment by Syncriix** [comment]
Relaxing all windows permission I know of didn't help, on the pdf, the whole c:/bin folder and its contents.
It is great to know that it will work on the production system though 😄 
The actual interesting part is that the same code worked for weeks with pdfs made from various other sources. It only fails if the customer sends an image file and apparently is run on windows...

**Comment by Belval** [comment]
From re-checking your output, something is wrong with the PDF path. pdfinfo's output should match the one you pasted yet it seems to print the usage instead.

You might want to make sure that the path given to the `convert_from_path` call does not have any typos? Also try with a file that does not have spaces in the name. It should not change anything in Linux but maybe Windows is different.

**Comment by Syncriix** [comment]
https://i.imgur.com/DzvgIUx.png
https://i.imgur.com/cFtwmiR.png

It is the exact same file, the same input format works with pdfs converted from docx, rtf, etc.

**Comment by Syncriix** [comment]
Ahaha, oh my god

Try feeding it a list instead of a string - there lies the answer! 🤦‍♂ 

I'm gonna blame it on all the Champagne during new years eve.
Still, usually packages catch wrong types with a more obvious error :) Maybe think about adding such for future me's, thank you for your time!

**Comment by rawatraghav** [comment]
> Ahaha, oh my god
> 
> Try feeding it a list instead of a string - there lies the answer! 🤦‍♂
> 
> I'm gonna blame it on all the Champagne during new years eve.
> Still, usually packages catch wrong types with a more obvious error :) Maybe think about adding such for future me's, thank you for your time!

Hey @Syncriix , Could you please elaborate on the solution to the problem? In which script and where exactly do we need to feed a list instead of a string? Struggling with the same problem ☹

**Comment by Belval** [comment]
@rawatraghav his error was that he was giving `convert_from_path` a list instead of a string for the `pdf_path`.

Make sure the poppler is installed on your system before anything else.

**Comment by MadanMaram** [comment]
from pdf2image import convert_from_path

PDF_file = 'Statement.pdf'
pages = convert_from_path(PDF_file, 500,userpw='01Apr!1126')

image_counter = 1

for page in pages:
    # create Retrive folder
    filename = "foldername/page_" + str(image_counter) + ".jpg"

    # Save the image of the page in system
    page.save(filename, 'JPEG')

    # Increment the counter to update filename
    image_counter = image_counter + 1

**Comment by GCMeccariello** [comment]
@Namyalg Do you find a solution? I am facing the same problem

**Comment by Belval** [comment]
@GCMeccariello is the `poppler` library installed on your system? In a managed environment like Heroku, it is likely that you don't have it installed by default.

See: https://github.com/Belval/pdf2image#how-to-install
