### ISSUE TITLE
generator already executing

### ISSUE THREAD

**Issue by L3o-pold** [Belval/pdf2image#121]
**Describe the bug**
`ValueError: generator already executing`

**To Reproduce**
Make a lot of conversion maybe?

**Expected behavior**
No error

**Desktop (please complete the following information):**
 - OS: Docker python:3.7-stretch
 - Version 1.11.0

Code:

Where `pdf` var is a `typing.IO[bytes]` stream

```python
pdf_content = pdf.read() 
images = convert_from_bytes(pdf_content)
```

Output:

```
File "/usr/local/lib/python3.7/site-packages/****, line ****, in ****
images = convert_from_bytes(pdf_content)
File "/usr/local/lib/python3.7/site-packages/pdf2image/pdf2image.py", line 269, in convert_from_bytes
 paths_only=paths_only,
 File "/usr/local/lib/python3.7/site-packages/pdf2image/pdf2image.py", line 144, in convert_from_path
thread_output_file = next(output_file)
ValueError: generator already executing
```

**Comment by Belval** [comment]
I think I will need more information in order to help with this issue.

Can you provide a snippet of the code used? This seems to indicate a weird race-condition but I hardly see how it could happen.

**Comment by L3o-pold** [comment]
It came from this project https://github.com/algoo/preview-generator/blob/develop/preview_generator/preview/builder/pdf__pypdf2.py#L56

On top of that I have a multithreaded webserver.

**Comment by Belval** [comment]
Does it only happen with a specific PDF or with any PDF?

**Comment by L3o-pold** [comment]
I'll not say any PDF, but a lot.

**Comment by L3o-pold** [comment]
By the way I see a lot of process that consuming a lot of memory and never ends to execute:

````
****      3537  0.3  0.0 124532 65744 ?        S    14:34   0:10 pdftoppm -r 200 /tmp/**** -f 1 -l 1
****      3755  0.3  0.0 111372 52884 ?        S    14:36   0:08 pdftoppm -r 200 /tmp/**** -f 1 -l 1
****      4087  0.0  0.0 161448 102204 ?       S    14:40   0:02 pdftoppm -r 200 /tmp/**** -f 1 -l 1
****      4101  0.0  0.0  83104 24196 ?        S    14:40   0:00 pdftoppm -r 200 /tmp/**** -f 1 -l 1
****      4119  0.0  0.0 103892 44852 ?        S    14:40   0:00 pdftoppm -r 200 /tmp/**** -f 1 -l 1
****      4143  0.0  0.0  82148 23052 ?        S    14:40   0:00 pdftoppm -r 200 /tmp/**** -f 1 -l 1
****      4164  0.0  0.0 123084 51272 ?        S    14:41   0:01 pdftoppm -r 200 /tmp/**** -f 1 -l 1
```

**Comment by Belval** [comment]
Hmm I am not able to reproduce the issue on my side, what webserver are you using?

**Comment by L3o-pold** [comment]
@Belval I just switched to Tornado and the problem seems fixed.
I also added a timeout in `communicate`method in your `pdf2image` lib.

**Comment by Belval** [comment]
The timeout is a good idea, if the problem is reported again I will consider adding one by default or at least making it a parameter.
