### ISSUE TITLE
Cropping PDF page just to fit content

### ISSUE THREAD

**Issue by rangathedon** [Belval/pdf2image#131]
Is there any way to crop the unused whitespace in the PDF before saving as image? I use the image to print on a thermal printer and lot of paper gets wasted because of the empty whitespace not getting cropped; the PDF itself comes from a third party and there is no way they can crop it at their end as they have fixed page sizes;

**Comment by Belval** [comment]
This is not really applicable to `pdf2image` as the goal of the module is to convert PDF into images.

That being said, the output format of `pdf2image` is a Pillow image. You should be able to crop those by following this SO question: https://stackoverflow.com/questions/10615901/trim-whitespace-using-pil
