### ISSUE TITLE
convert_from_path to an Output folder hangs when deployed as a Apache API

### ISSUE THREAD

**Issue by ashwarhussain** [Belval/pdf2image#135]
Dear Belval,

Hope you are doing great in these virus times. Developers can hide from Virus but from bugs probably no. Here is a something that we think is a bug (obviously after your approval).

Context: we are using pdf2Image to convert a PDF into Images per page and then we teseract these images to get a transcript. We do this for scanned PDF files where standard PDF packages are not able to extract text.
 
We have deployed this PY code as an APACHE API and from our UI(.NET) we call this Apache API for text extraction. 

When this code runs all alone without anything running on Apache it works very well, BUT when Apache is paralell processing something else and convert_from_path also comes up them Apache is getting hung with any response.

Environment: 

PY - 3.6
pdf2image==1.11.0
[root@a81ca235dccb /]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"

**Source code that we use is the below ... can you please help us out.**
os.makedirs(output_folder_path)
try:
	self._log_helper.write_log_per_file(filename, "1*1")
	**pages = convert_from_path(file_path, dpi=300,thread_count=4 ,output_folder=output_folder_path)**
	self._log_helper.write_log_per_file(filename, "2*2")
	print("no of pages = " + str(len(pages)))
	self._log_helper.write_log_per_file(filename,"no of pages = " + str(len(pages)))
    if(len(pages)) <= int(scannedpdf_pagelimit):
		for idx, page in enumerate(pages):
			pagename = output_folder_path +'/'+ 'page' + str(idx) + '.jpg'
			print("pagename is:",pagename)
			page.save(pagename, 'JPEG')
			os.chmod(pagename, 0o777)
			**conversionStatus = os.system('tesseract ' + pagename + ' ' + output_folder_path + "/output")**
			if conversionStatus == 0:
				print("Converted image to text")
				f = codecs.open(output_folder_path + "/output.txt", 'r', encoding='utf-8')
				text = f.read()
				f.close()

**Comment by Belval** [comment]
I'll try to reproduce the issue on my side, hang on.

**Comment by ashwarhussain** [comment]
To update you .. we have now updated pdf2Image and we are using 1.12.1 
change the code to extract images as below to deal with 5 pages in 1 shot
or page in range(1,pages_count,5):
                    pages = convert_from_path(file_path, dpi=300,first_page=page,
                                                     last_page=min(page + 5 - 1, pages_count), fmt= 'jpeg',
                                                     thread_count=1, userpw=None,
                                                     use_cropbox=False, strict=False,output_folder=output_folder_path)

**Comment by Belval** [comment]
I was not able to reproduce the issue, can you try and bundle your application in a container so I can run it on my side?

It might be a regression because I already patched an issue with concurrent `pdf2image` usage.

**Comment by ashwarhussain** [comment]
Dear Belval,

its not about concurrent pdf2image usage but its about pdf2image getting hung when something else is running paralelly on the same Apache.

To give you more context say one Apache we are running pdf2image on one thread and on another thread concurrently we are running another PY program (more details below) then pdf2image is getting into hung state and apache is also getting hanged.

another PY service uses some standard packages like below and also reads some files from folder (not RAM).

from gensim import models
from dataLoader import LoadDataset
import random
import numpy as np
from collections import defaultdict
from tqdm import tqdm
from gensim.matutils import softcossim
from gensim import corpora
from copy import deepcopy
import pandas as pd
from PreProcessing import PreProcessing
import numpy as np
import xml.etree.ElementTree as ET
from nltk.stem.wordnet import WordNetLemmatizer
import pandas as pd

**Comment by Belval** [comment]
This is not directly related to `pdf2image` and has been inactive for a while. Closing.
