### ISSUE TITLE
dpi and size do not work together

### ISSUE THREAD

**Issue by vkonstantis** [Belval/pdf2image#141]
If you try the following:
`convert_from_path('path_to_pdf', dpi=600, size=400)`
the function returns instantly,  the dpi parameter is ignored and the image quality is bad.

If you try without the size:
`convert_from_path('path_to_pdf', dpi=600)`
the processing takes a lot more time and the end quality of the image is great.

Maybe there should be a warning that these two parameters do not work together.

**Comment by Belval** [comment]
I will try it on my side, but this is probably the desired behavior, dpi only means something if you don't have an explicit size, as it is a way to extrapolate an image size from the paper format.

**Comment by Belval** [comment]
I just tested it and I think I would classify it as a documentation issue if anything. `pdf2image` is just a wrapper around poppler and in this case the behavior is in line with the library.

Feel free to suggest another way we could handle the conflicting parameters.

**Comment by vkonstantis** [comment]
I agree with you. If someone wants to set the dpi and scale the pdf he/she should use another tool for scaling. (e.g. convert from ImageMagick) since it is not possible to do this at the same time with poppler's pdftoppm/pdftocairo.
