### ISSUE TITLE
Layered PDF converts to blank images

### ISSUE THREAD

**Issue by oschwartz10612** [Belval/pdf2image#143]
I looked though the issues here and was unable to find a similar issue, but if this has been solved previously I apologized. Similarly I was unsure if this was a bug so I did not want to report it as such.

pdf2image will convert the PDF correctly if it is exported by "printing to a PDF" essentially "flattening" the PDF. If not printed to a PDF first, the first page converts correctly, but the second two become white pages. Thus we believe that this is layer issue. Maybe there is a way to flatten the layers first, or we are missing an option in pdf2image?

This is the PDF we are having issues with:
[oneword.pdf](https://github.com/Belval/pdf2image/files/4707847/oneword.pdf)

Thank you!

**Comment by Belval** [comment]
Hi,

Thank you for providing a sample PDF right off the bat, it helps a lot when troubleshooting. Unfortunately, I am unable to reproduce the issue you describe. When converting the document I get the two pages below which seems to be the expected results. With what parameters are you calling `convert_from_path`? 

![oneword-2](https://user-images.githubusercontent.com/5399488/83365955-1a409880-a37a-11ea-92d2-40c06c01e07b.png)
![oneword-3](https://user-images.githubusercontent.com/5399488/83365956-1ad92f00-a37a-11ea-9080-413736a2324c.png)

**Comment by oschwartz10612** [comment]
Thanks for the quick reply! We appreciate it.

That is odd. I pasted our code below. We are using Windows.

```python
convert_from_path(              
pdf_path = (subfolder + "/" + "no_text_" + filename), 
output_folder = subfolder,
fmt = "png",
output_file = (f"no_text_{filename}")
)
```
Thanks again.

**Comment by Belval** [comment]
I can confirm that using your code I get the expected output. I see two possibles problems:

- The file you provided is the one that was flattened
- The bug was fixed in a later version of poppler (I'm on 0.88.0)

**Comment by oschwartz10612** [comment]
The PDF is correct. We double checked.

It appears that the latest Poppler for Windows build is 0.68.0. Is there a binary fir 0.88.0?

**Comment by Belval** [comment]
Not directly downloadable no.

But if you are willing to try it out, you can use the `poppler` package in a `conda` environment. If you are able to convert your file with that, it would confirm that the poppler version is to blame.

This section of the README should help: https://github.com/Belval/pdf2image#platform-independant-using-conda

**Comment by oschwartz10612** [comment]
I was able to confirm on a OSX machine with the latest poppler build that it does indeed work properly. We are experiencing issues with conda on the Windows machine, though I will get back to you shortly. Is there any chance you have a Windows build that you could share of a newer version?

**Comment by Belval** [comment]
I never really used `pdf2image` on Windows except when troubleshooting issues.

Your best bet would be to look into the conda build pipeline here: https://github.com/conda-forge/poppler-feedstock, you could raise the issue with them.

**Comment by oschwartz10612** [comment]
We were able to get conda working and were able to confirm that the poppler version was the issue. The PDF converts correctly on 0.89.0.

If it helps anyone, these is the latest compiled poppler version for Windows: 
[poppler-0.89.0.zip](https://github.com/Belval/pdf2image/files/4719380/poppler-0.89.0.zip)

Closing because the issue was solved. Thank you!

**Comment by Belval** [comment]
Glad you got it sorted out! I am curious, where did you get that compiled version of poppler? I often get request for precompiled binaries.

**Comment by oschwartz10612** [comment]
I pulled it together from the conda install by looking at its dependencies. I may have missed something, so let me know and I will fix it.
