### ISSUE TITLE
Difference between convert_from_path on windows and linux

### ISSUE THREAD

**Issue by ChungNPH** [Belval/pdf2image#144]
Hi guys, I used convert_from_path to generate JPEG image from pdf file, but their resolution are different. Please tell me reason and how can i fix it? Thank you so much!

**Comment by ChungNPH** [comment]
I used same code on 2 os.

**Comment by Belval** [comment]
Unfortunately this is not necessarily related to `pdf2image` or even poppler. You can try to pass `jpegopt={"quality": 100}` to reduce the compeession level and get better matching results. 

Beyond that, I can't do much. Make sure that your poppler version are the same, take them both from the `conda-forge` as this will increase your chances of having the same underlying jpeg library (libjpeg vs libjpeg-turbo).

**Comment by ChungNPH** [comment]
Thank you so much, i will check it!
