### ISSUE TITLE
PDF to TIFF conversion returns a file not found error

### ISSUE THREAD

**Issue by Elephant940** [Belval/pdf2image#145]
This issue is working with the same pdf and program that oschwartz10612 opened a few days ago.  
As they said, we were able to get the program to produce images rather than white squares. However, this only works with certain types of image files.  I've been using PNG as the output format, however there is always a noticeable level of compression in the final pdf (the program converts the pdf to images for editing, then converts the images back into a pdf).  
When I use TIFF, ultimately the format I'd like to use, the following error is returned.

`C:\Users\eleph>C:/Python/Python38/python.exe "c:/Users/eleph/Documents/My Documents/CROTEK/Workspace/Algorithm for Correcting Scanned Documents/main_and_ocr.py"
Traceback (most recent call last):
  File "c:/Users/eleph/Documents/My Documents/CROTEK/Workspace/Algorithm for Correcting Scanned Documents/main_and_ocr.py", line 82, in <module>
    convert_from_path(
  File "C:\Python\Python38\lib\site-packages\pdf2image\pdf2image.py", line 108, in convert_from_path
    poppler_version = _get_poppler_version(
  File "C:\Python\Python38\lib\site-packages\pdf2image\pdf2image.py", line 394, in _get_poppler_version
    proc = Popen(command, env=env, stdout=PIPE, stderr=PIPE)
  File "C:\Python\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified`

Here is the part of the code that converts the pdf to images.

`convert_from_path(
                            pdf_path = (subfolder + "/" + "no_text_" + filename), 
                            output_folder = subfolder,
                            fmt = "tiff",
                            output_file = (f"no_text_{filename}")
                            )`

Lastly, here is the pdf: https://github.com/Belval/pdf2image/files/4707847/oneword.pdf 

I'm using Windows 10. I'm relatively new to coding, so if there's any important information I've accidentally excluded please let me know.  Any help you could provide would be greatly appreciated.

Edit: I just realized the error I pasted is really difficult to read, but I'm unsure of how to format it well while keeping it in the code format.  My sincerest apologies.

**Comment by Belval** [comment]
Hi!

Thank you for providing an error message, it always makes it much easier to help.

In your case the issue seems to be that `poppler` is not installed on you machine. You see, `pdf2image` is only a wrapper around it and as such, there are a few manual steps to do before successfully converting a PDF.

See: https://github.com/Belval/pdf2image#windows for how to use and install poppler.

**Comment by Elephant940** [comment]
Oh no worries! Yes, only the TIFF format.  oschwartz10612 gave me this poppler file to download, which I then moved to the appropriate place in miniconda.  There's a tiff.dll file in this zip, which I thought would make the TIFF conversion execute correctly, but alas it does not. Perhaps there is another missing file?

https://github.com/Belval/pdf2image/files/4719380/poppler-0.89.0.zip

**Comment by Belval** [comment]
I figured it out! Unfortunately, the package linked in the other thread does not include `pdftocairo`, which is the utility that supports conversion to the TIFF format. 

The only solution I see is the get a new build that includes `pdftocairo`. Maybe @oschwartz10612 can help as I never went through the whole process.

**Comment by oschwartz10612** [comment]
It seems that conda is not building `pdftocairo` for some reason. Poppler would need to be built manually from source. I can look into it but it is not a walk in the park. 

Alternatively, you could try this not very elegantly smashed together version of 0.68.0 and 0.89.0. I would presume that you will continue to experience #143 as it is not the latest build.
[poppler-0.89.0.zip](https://github.com/Belval/pdf2image/files/4733555/poppler-0.89.0.zip)

**Comment by Belval** [comment]
Actually it's possible the `pdftocairo` would not have the same issue as `pdftoppm` as it is not exactly the same codebase. I'll try it right now.

**Comment by Belval** [comment]
Yeah doesn't seem to work unfortunately.

**Comment by oschwartz10612** [comment]
Okay. I am attempting to build from source but I am very much out of my comfort zone. I will try to update tomorrow. 

Seems a the chocolaty build also does not include `pdftoppm`

**Comment by oschwartz10612** [comment]
I think @Elephant940 might need to run Poppler in WSL.

**Comment by Belval** [comment]
That is a great idea, @Elephant940 see [this Microsoft article](https://docs.microsoft.com/en-us/windows/wsl/install-win10) on how to setup WSL on your machine. It's like having a small Linux (Ubuntu) terminal inside your Windows install which allows you to run Linux-specific stuff. Once that install you will be able to just `sudo apt install poppler-utils` and convert your documents.

**Comment by Elephant940** [comment]
Oh okay, thank you so much for your help.  I'll try WSL.

**Comment by oschwartz10612** [comment]
Using WSL solves this issue. Until poppler is build with pdftocairo for Windows this will remain an issue.

**Comment by oschwartz10612** [comment]
This was fixed in conda-forge/poppler-feedstock#67. You can download using conda or the packaged version here: https://github.com/oschwartz10612/poppler-windows

**Comment by Belval** [comment]
Thank you so much @oschwartz10612 I will update the README today to make sure to point Windows users to your repo instead of the other website.

**Comment by oschwartz10612** [comment]
No problem. Thanks for working with us!

Let me know if people have issues with the repo.
