### ISSUE TITLE
pdf2image.exceptions.PDFPageCountError when file path too long

### ISSUE THREAD

**Issue by vinhtq115** [Belval/pdf2image#149]
**Describe the bug**
When path-to-file is too long (I guess over 256 characters), I got `pdf2image.exceptions.PDFPageCountError`

**To Reproduce**
1. Set file path to something longer than 256 and use `pdfinfo_from_path` or `convert_from_path`
2. See error

**Expected behavior**
Should not show any exceptions.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
I tested with a path about 240 characters and the error did not happen. The one I tried to trigger the error was about 264 characters.

**Comment by Belval** [comment]
Hi!

Unfortunately, this is not related to pdf2image/poppler. It's a limitation on Windows.

If you feel hacky, you can lift the limit by editing your registry: https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/
