### ISSUE TITLE
Error while generating TIFF-Output

### ISSUE THREAD

**Issue by p2k-ko** [Belval/pdf2image#155]
When using *pdf2image* with the TIFF-Format for output we encounter the followning Errors:

```
images = pdf2image.convert_from_path('c:\\temp\\a.pdf', fmt='tiff', output_folder='c:\\temp\\')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\pdf2image\pdf2image.py", line 199, in convert_from_path
    output_folder, uid, final_extension, paths_only, in_memory=auto_temp_dir
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\pdf2image\pdf2image.py", line 471, in _load_from_output_folder
    images.append(Image.open(os.path.join(output_folder, f)))
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\PIL\Image.py", line 2931, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file 'c:\\temp\\f11617de-eb1e-4db1-b6d5-55be74004c1e-1.tif'
```

The generated TIFF-Files in the output folder have a file size of 0 Byte:

![grafik](https://user-images.githubusercontent.com/5457328/89402778-a6bf5c80-d717-11ea-8445-69ddbd527765.png)

If we change the output format to ```fmt='png'``` the conversion works as expected:

![grafik](https://user-images.githubusercontent.com/5457328/89402952-ebe38e80-d717-11ea-8f4a-8dffb062196f.png)

I am using the latest poppler version from  @oschwartz10612/poppler-windows .

```
c:\temp>pdfinfo -v
pdfinfo version 0.90.1
Copyright 2005-2020 The Poppler Developers - http://poppler.freedesktop.org
Copyright 1996-2011 Glyph & Cog, LLC
```

 I'm not sure if the error originates in  *pdf2image* or poppler. At some stage the output file is not written and remains empty. 

**Desktop (please complete the following information):**
 - Python: 3.7.0
 - pip: 20.2.1
 - pdf2image: 1.13.1
 - pillow: 7.2.0
 - poppler: 0.90.1

**Comment by Stupesmith** [comment]
Hello,

I have the exact same problem (I'm on Win10).
I have the same versions installed.
I installed pdf2image 1.14.0, still same problem.
I tried the poppler install from conda and directly from the release @oschwartz10612/poppler-windows.

Did you, by any chance, resolve your issue ?

**Comment by p2k-ko** [comment]
I did some testing this morning. I think it is an upstream problem and directly related to `pdf2image`. In case of `tiff` as the image format `pdf2image` uses `pdftocairo` from *poppler*. I tried to convert a PDF file directly with `pdftocairo`:

```
(venv) λ pdftocairo.exe -tiff example.pdf
(venv) λ dir
 Datenträger in Laufwerk D: ist Daten

 Verzeichnis von D:\pdf2image_test

28.08.2020  11:15    <DIR>          .
28.08.2020  11:15    <DIR>          ..
28.08.2020  11:15                 0 example-1.tif
01.07.2020  11:36           761.716 example.pdf
28.08.2020  11:00    <DIR>          poppler
28.08.2020  11:00         6.978.908 release.zip
28.08.2020  10:57    <DIR>          venv
               3 Datei(en),      7.740.624 Bytes
               4 Verzeichnis(se), 16.847.187.968 Bytes frei

D:\pdf2image_test
```
In my case the resulting file of `pdftocairo` is empty. Therefore the problem is not within `pdf2image`  and I close this issue here and open a new issue @oschwartz10612/poppler-windows after checking if the poppler on Linux is able to create `tiff`-Files. 

Best regards
Stephan
