### ISSUE TITLE
PDFInfoNotInstalledError: Unable to get page count. Is poppler installed and in PATH?

### ISSUE THREAD

**Issue by mahesh1amour** [Belval/pdf2image#163]
Im using PDF2image library for converting pdf to image in windows  as follows

**
    import os
    import pdf2image
    from PIL import Image

    def pdftoimage(filePath, imageResolution, index):

        FORMAT = 'jpg'
        THREAD_COUNT = 1
        OUTPUT_FOLDER = r"C:\Users\00005011\Documents\XXX"
        pil_images = pdf2image.convert_from_path(filePath, dpi=imageResolution, fmt=".jpg", thread_count=THREAD_COUNT)
        #This method helps in converting the images in PIL Image file format to the required image format
        for image in pil_images:
               index += 1

               image.save(os.path.join(OUTPUT_FOLDER,f"image-{index}.jpg"))
        return OUTPUT_FOLDER , index

      filePath = r"C:\Users\00005011\Documents\XXX.pdf"
      print(os.path.exists(filePath))

      pdftoimage(filePath, 300, 1)**

but im getting error as 
**FileNotFoundError                         Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\pdf2image\pdf2image.py in pdfinfo_from_path(pdf_path, userpw, poppler_path, rawdates, timeout)
    440             env["LD_LIBRARY_PATH"] = poppler_path + ":" + env.get("LD_LIBRARY_PATH", "")
--> 441         proc = Popen(command, env=env, stdout=PIPE, stderr=PIPE)
    442 

C:\ProgramData\Anaconda3\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors, text)
    774                                 errread, errwrite,
--> 775                                 restore_signals, start_new_session)
    776         except:

C:\ProgramData\Anaconda3\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
   1177                                          os.fspath(cwd) if cwd is not None else None,
-> 1178                                          startupinfo)
   1179             finally:

FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

PDFInfoNotInstalledError                  Traceback (most recent call last)
<ipython-input-17-d73debed109a> in <module>
     19 os.path.exists(filePath)
     20 
---> 21 pdftoimage(filePath, 300, 1)

<ipython-input-17-d73debed109a> in pdftoimage(filePath, imageResolution, index)
      8     THREAD_COUNT = 1
      9     OUTPUT_FOLDER = r"C:\Users\00005011\Documents\Table_Extraction\TestCases"
---> 10     pil_images = pdf2image.convert_from_path(filePath, dpi=imageResolution, fmt=".jpg", thread_count=THREAD_COUNT)
     11     #This method helps in converting the images in PIL Image file format to the required image format
     12     for image in pil_images:

C:\ProgramData\Anaconda3\lib\site-packages\pdf2image\pdf2image.py in convert_from_path(pdf_path, dpi, output_folder, first_page, last_page, fmt, jpegopt, thread_count, userpw, use_cropbox, strict, transparent, single_file, output_file, poppler_path, grayscale, size, paths_only, use_pdftocairo, timeout)
     95         poppler_path = poppler_path.as_posix()
     96 
---> 97     page_count = pdfinfo_from_path(pdf_path, userpw, poppler_path=poppler_path)["Pages"]
     98 
     99     # We start by getting the output format, the buffer processing function and if we need pdftocairo

C:\ProgramData\Anaconda3\lib\site-packages\pdf2image\pdf2image.py in pdfinfo_from_path(pdf_path, userpw, poppler_path, rawdates, timeout)
    466     except OSError:
    467         raise PDFInfoNotInstalledError(
--> 468             "Unable to get page count. Is poppler installed and in PATH?"
    469         )
    470     except ValueError:

PDFInfoNotInstalledError: Unable to get page count. Is poppler installed and in PATH?
**

![Capture](https://user-images.githubusercontent.com/42795522/91836007-d0f93100-ec67-11ea-8d57-cd192c14cfcc.PNG)

**Comment by Belval** [comment]
Please make sure that poppler is installed on your system. You can refer to this stackoverflow thread for a better explanation:

https://stackoverflow.com/questions/53481088/poppler-in-path-for-pdf2image/53539577?noredirect=1#comment112878561_53539577

**Comment by bharath-kumarn** [comment]
formsense-microservice_1  |     images = convert_from_path(file)
formsense-microservice_1  |   File "/usr/local/lib/python3.6/site-packages/pdf2image/pdf2image.py", line 98, in convert_from_path
formsense-microservice_1  |     page_count = pdfinfo_from_path(pdf_path, userpw, poppler_path=poppler_path)["Pages"]
formsense-microservice_1  |   File "/usr/local/lib/python3.6/site-packages/pdf2image/pdf2image.py", line 485, in pdfinfo_from_path
formsense-microservice_1  |     "Unable to get page count. Is poppler installed and in PATH?"
formsense-microservice_1  | pdf2image.exceptions.PDFInfoNotInstalledError: Unable to get page count. Is poppler installed and in PATH?

**Comment by lCrashl** [comment]
I have the same issue. I can get the error resolved:

`pdf2image.exceptions.PDFInfoNotInstalledError: Unable to get page count. Is poppler installed and in PATH?`

I have poppler installed with `conda install -c conda-forge poppler` and I have the Github version in my `/ProgrameFiles/poppler-23.10.0`

Conda folder and `/ProgrameFiles/poppler-23.10.0` are in PATH. 

Any ideas?
