### ISSUE TITLE
pdf2image not converting jpegs inside PDF

### ISSUE THREAD

**Issue by Erkhembayaar** [Belval/pdf2image#166]
Hello,
I tried enabling usepdfcairo and cropbox and it still didnt work, I attached a file 

[46474.pdf](https://github.com/Belval/pdf2image/files/5285975/46474.pdf)

    combined_pdf_pages = convert_from_path(output_path + '.pdf', dpi=200,output_folder=TEMP_FOLDER)

        for page in combined_pdf_pages:

            idx = idx + 1
            page.save(os.path.join(OUTPUT_PATH_JPG, str(idx) + ".jpg"), "JPEG")

**Comment by Belval** [comment]
> Hello,
> I tried enabling usepdfcairo and cropbox and it still didnt work, I attached a file
> 
> [46474.pdf](https://github.com/Belval/pdf2image/files/5285975/46474.pdf)
> 
> ```
> combined_pdf_pages = convert_from_path(output_path + '.pdf', dpi=200,output_folder=TEMP_FOLDER)
> 
>     for page in combined_pdf_pages:
> 
>         idx = idx + 1
>         page.save(os.path.join(OUTPUT_PATH_JPG, str(idx) + ".jpg"), "JPEG")
> ```

Hi! What OS are you running this on and what is the result you get?

**Comment by Erkhembayaar** [comment]
Hi, Windows 10, 64x. The result is just a blank white page. I attached the pdf file above

**Comment by Belval** [comment]
Just tried it on Windows 10 x64 with latest version of Poppler (the one in the README) and my result seems good:

![0](https://user-images.githubusercontent.com/5399488/94327240-8a9da600-ff77-11ea-8b7a-bb827e862241.png)

Here is my code:

```py
from pdf2image import convert_from_path

for i, img in enumerate(convert_from_path("./46474.pdf", poppler_path=r"C:\Users\Edouard\Git\repro\bin")):
    img.save(f"{i}.png")
```

And here is my directory hierarchy (not that it matters):

![image](https://user-images.githubusercontent.com/5399488/94327259-b0c34600-ff77-11ea-883b-67476b9f193f.png)

**Comment by Erkhembayaar** [comment]
May I ask your popplers version and where to get the latest version of it ?

**Comment by Belval** [comment]
Here's my version, and where I get it: https://github.com/oschwartz10612/poppler-windows/releases
