### ISSUE TITLE
pdf2image not working with gunicorn/flask

### ISSUE THREAD

**Issue by NameKhan72** [Belval/pdf2image#169]
Hello,

for the past day I have been trying to incorporate pdf2image into my flask webservice. The problem is, whatever I do, I still get the "Is poppler installed and in PATH?" error message. I have written a little program that just prints the number of pages in a pdf file. This works completely fine, inside and outside the venv containing flask. If I try to do this from the flask file, I get the error. I even tried calling the very same function in the test code, but to no avail. I don't really know what to do anymore, so any help is greatly appreciated.

P.S.: I don't really know what source to include for this post, so just feel free to ask and I will provide it.

**Comment by morenoh149** [comment]
I fully cloneable flask api would help.

**Comment by NameKhan72** [comment]
> I fully cloneable flask api would help.

I'm not sure that I fully understand. If you need the python file, here it is:


```python
from flask import Flask, request
from flask_restful import Resource, Api
from pdf2image import pdfinfo_from_bytes,convert_from_path, convert_from_bytes, pdfinfo_from_path




app = Flask(__name__)
api = Api(app)


class Convert(Resource):

    @staticmethod
    def post():
        path = r'Context_webcode_context-22.pdf'


        info = pdfinfo_from_path(path)

        print(info['Pages'])


api.add_resource(Convert, '/api/convert')



if __name__ == '__main__':
    app.run(debug=True)

```

**Comment by NameKhan72** [comment]
Well, I have edited pdf2image.py in such a way that it prints the actual error. 
The error I got was: [Errno 2] No such file or directory: 'pdfinfo': 'pdfinfo'
This is odd, as I can just type "pdfinfo" into the linux shell and it works.

**Comment by Belval** [comment]
This is usually due to gunicorn/flask preventing processes from being spawned inside their worker processes that are processing the request (that's an issue I had with Django + Gunicorn). 

Test the hypothesis by using `subprocess.Popen` directly in the API method to see if it raises the same issue. You can call any executable such as "ls". If that works then it probably means that the PATH variable is simply not set in gunicorn/flask processes. You can test that by printing `os.environ`to see if it's in there.

Happy debugging!

**Comment by NameKhan72** [comment]
First of all, thanks for the quick reply.
Indeed trying to call 
```python 
Popen(['ls'])
``` 
results in the same "file not found" error. 

Knowing the problem is good, however I have no Idea how to fix it. Is there any way?

**Comment by NameKhan72** [comment]
I figured it out! (yay)

So the issue was with the way python handles PATH and virtual environments.
With the virtual environment being, well virtual..., python doesn't pass the "real" system PATH to the os.environ variable. It creates it's own, which is the path to the "bin"-folder inside the venv. As pdfinfo is located in /usr/bin/pdfinfo, as can be seen by doing 'which pdfinfo'. 
Just doing:

```python

        if '/usr/bin' not in os.environ:
            os.environ['PATH'] = '/usr/bin'

```

Before calling the pdf2image method solves this problem. Now the venv has access to the real PATH of the machine.

Note: This replaces the "venv-path". If you rely on it, you have to take this into consideration.

**Comment by Belval** [comment]
Thank you for taking the time to update the issue. This question comes up semi-often and it will surely be helpful to people in the future.
