### ISSUE TITLE
pdf2image converts only the last page of a 20 page pdf file

### ISSUE THREAD

**Issue by smehra69** [Belval/pdf2image#177]
I am using pdf2image to convert a 20 pge long pdf file. however I have only the last page saved as output.
How to get all the pages?
The code is as follows:-

from pdf2image import convert_from_path 
images = convert_from_path('test_man.pdf')
for img in images:
    img.save('outputpdf.jpg', 'JPEG')

**Comment by Belval** [comment]
Hmm I could be wrong, but you seem to be overwriting the output file with every `save()`. Try

```py
from pdf2image import convert_from_path
images = convert_from_path('test_man.pdf')
for i, img in enumerate(images):
    img.save(f'output-{i}.jpg', 'JPEG')
```
