### ISSUE TITLE
Don't scale up small images

### ISSUE THREAD

**Issue by AlexanderMatveev** [Belval/pdf2image#182]
I'm using `size=2000` parameter to fit big pages to 2000x2000 image. How can I skip sizing up images smaller than 2000x2000?

This advice #93 is not my way because i'm using `thread_count` parameter to speed up converting. But assigning function result to array for iteration slows everything down to one thread speed.

**Comment by Belval** [comment]
Hmm I don't see how that can be fixed as it's dependant on the underlying `pdftoppm`/`pdftocairo` implementation. 

I am however puzzled by your claim that iterating through the results will make it single threaded. It should not work that way and #93 should be applicable to your use case. Can you share a snippet of how you call `pdf2image`? I'll try to reproduce the issue.

**Comment by AlexanderMatveev** [comment]
I moved to parallel executing `pdftocairo` with `-f` and `-l` parameters from main application stack (which is Golang) from idea to create a Python containered microservice. 

Unfortunatelly, I didn't save my code and measuring results, but code was the same as first code example in #93.

@Belval thank you for trying to help and for this brilliant package, which made me look to `pdftocairo`/`poppler-utils`.
