### ISSUE TITLE
No bounds checking on first_page parameter

### ISSUE THREAD

**Issue by zweissman** [Belval/pdf2image#184]
**Describe the bug**
There does not look to be any validation on the first_page parameter. The last_page is checked to see if it is greater than page_count and if it is, it is set to page_count. Great. I had set my first_page = 0 since that is what I had been using in pdftoppm (can't remember if there was a reason I did that or not). Looks like your code and thread logic is expecting that the first page is never less than 1.

FYI, if you do set the first_page to 0 and your thread_count > page_count, it will run the pdf twice. The first will all run on the first thread, and then the second copy will have one page per thread. My configuration was thread_count 6 on a page_count 5 pdf and got 10 images total, two for each page.

Setting first_page = 1 fixes the issues, but it would be simple enough to add a first_page <= 1 : first_page = 1 in there.

**Comment by Belval** [comment]
There should be bound checking on first page. I don't have much bandwidth right now but if someone wants to fix it, it should be pretty easy to add a check in `convert_from_path`  and `convert_from_bytes` next to where bound checking is done for `last_page`.

**Comment by zweissman** [comment]
PR #185 submitted

**Comment by Belval** [comment]
I merged the PR, will release a new version soon.
