### ISSUE TITLE
Documentation Error with usage of setGMClass()

### ISSUE THREAD

**Issue by karljinang** [Belval/pdf2image#190]
**Describe the bug**
Documentation error.

For indicating that image magick is used, current docs says to do
`const convert = fromPath(filePath, options).setGMClass(true)`

When doing this `convert` is undefined.

The proper example in docs should be

```
const convert = fromPath(filePath, options);
convert.setGMClass(true);

// use convert here ....
```

**Comment by Belval** [comment]
I am not completely sure but I think you are looking for the pdf2image module for JavaScript. The repo is here (I think?): https://bitbucket.org/RicardoCacheira/pdf2image/src/master/
