### ISSUE TITLE
unwanted suffix in output filename

### ISSUE THREAD

**Issue by fluviotect** [Belval/pdf2image#196]
"0001-1" is appended to the prefix of my outfile names. For example:
    
    Infilename0001-1.png

** to reproduce **
```
file = "Infilename.pdf"
convert_from_path(inpath+file,dpi=600, output_folder=outpath,fmt='png',use_cropbox=True,output_file=os.path.splitext(file)[0])
```

**Expected behavior**
"Infilename.png"

**Desktop (please complete the following information):**
 - Python v 3.7
 - OS: Windows 7 Pro
 - Browser: Firefox
 - pdf2image Version: 1.13.1

**Additional context**
Obviously, I can parse it out, but would be nice not to be less verbose.

**Comment by Belval** [comment]
That is caused by the underlying PDF rasterizing library so it cannot be addressed easily in `pdf2image`. Feel free to reopen if you have other questions.

**Comment by fluviotect** [comment]
No worries.  Cheers for reply.
