### ISSUE TITLE
unable to import pdf2image

### ISSUE THREAD

**Issue by jontang** [Belval/pdf2image#2]
I'm on a mac osx 10.12 using python 3.6.1 and used pip3 to install pdf2image. Prior to installation, I installed poppler using brew.  After installation, it said that pdf2image-0.1.5 was successfully installed. But, when I try to import pdf2image, I get the following error:
 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pdf2image'

Is there another requirement I'm missing?

**Comment by Belval** [comment]
Do you have Pillow?

’pip3 install pillow’

I updated the readme yesterday but I'll add it as a requirement in 0.1.6.

**Comment by jontang** [comment]
yeah, I do have pillow installed

**Comment by Belval** [comment]
First as a sanity check, create a virtualenv, and reinstall both PIL and pdf2image.

```
pip3 install virtualenv
virtualenv -p python3 envname
source envname/bin/activate
pip3 install pillow
pip3 install pdf2image
python3
>>> import pdf2image
```


Please tell me if it works, I do not own a Mac...

**Comment by Belval** [comment]
Closing issue for lack of response. Feel free to reopen should the error happen again.

**Comment by Salma-El-Alem** [comment]
I wrote my code and I used pdf2image package and now I'm trying to link this class with my django project but it's not able to import the package 
python version 3.8

**Comment by Belval** [comment]
What is your error message/stack trace?

**Comment by Salma-El-Alem** [comment]
pylint(no-member)

**Comment by Belval** [comment]
I am afraid I will need a test case otherwise I cannot help much.

**Comment by NahinKhan113** [comment]
Hi, I am also facing the same problem, and not getting any correct solution.

**Comment by franckberneron** [comment]
Hi Edouard,
I am also getting the same ModuleNotFoundError: No module named 'pdf2image' error.
![image](https://user-images.githubusercontent.com/47366873/157975569-a8334150-6d02-4ac1-b889-f90187e89141.png)

The module is indeed installed in my virtualenv :
![image](https://user-images.githubusercontent.com/47366873/157975751-51a003b6-fe5c-44b6-90fd-f0b71d4d5057.png)

I'm running Ubuntu 16.04 on a Win10 WSL2.

Any help much appreciated
