### ISSUE TITLE
Error 'pdfinfo'

### ISSUE THREAD

**Issue by 3y3y3y** [Belval/pdf2image#20]
Hello! I am using your pdf2image function to convert a pdf file to images but it turns out that there is an error.  
proc = Popen(["pdfinfo", pdf_path], stdout=PIPE, stderr=PIPE)
FileNotFoundError: [Errno 2] No such file or directory: 'pdfinfo'
I have checked the Popen() function's documentation and the first element in the table should be the address for an executable process. Could you tell me where exist the 'pdfinfo' file?
Thank you very much!

**Comment by rjsmethurst** [comment]
I am having the exact same problem! 

```FileNotFoundError: [Errno 2] No such file or directory: 'pdfinfo'``` 

when I try using either ```convert_from_path``` or ```convert_from_bytes```

**Comment by Belval** [comment]
Did you both install `poppler-utils` first?

**Comment by macqueen09** [comment]
> Did you both install `poppler-utils` first?
> 
> EDIT: Just to clarify, `pdfinfo` is an executable used by poppler (and therefore by pdf2image). Normally it should come with the poppler-utils package on Ubuntu.

great .! Thanks !  
solved the problem after `apt install poppler-utils`
