### ISSUE TITLE
please upload 1.16.0 .tar.gz as well

### ISSUE THREAD

**Issue by mapreri** [Belval/pdf2image#202]
Hi!

in your loast update in pypi, you only uploaded the wheel without the accompanying sources.

Could you also push the sdist? :)  Thank you in advance!

**Comment by Belval** [comment]
Thank you for raising this issue, `pdf2image-1.16.0.tar.gz` should now be available in PyPI (their cache can take 30 minutes to update).

**Comment by mapreri** [comment]
it's there, thank you!
