### ISSUE TITLE
pdftoppm chenge freetype font

### ISSUE THREAD

**Issue by kbrajwani** [Belval/pdf2image#203]
Can i know which fonts is used by pdftoppm by default and how can we change it?
i just want to use one arial font rather than the default font.

**Comment by Belval** [comment]
There is not option built-in to do so in `pdf2image`. The default font for pdftoppm is probably dependent on your OS.

As far as implementing it in `pdf2image`, I am not sure that it possible neither `pdftoppm` nor `pdftocairo` implement font override.
