### ISSUE TITLE
pdf to tiff converting only first page

### ISSUE THREAD

**Issue by frederick0291** [Belval/pdf2image#206]
**Describe the bug**
Converting pdf to TIFF only converts first page. I tried adding first and last pages, I also tried using even or odd pages but still only the first page gets converted.

**To Reproduce**
On python: ` convert_from_path(file, output_folder=outdir, poppler_path = poppler_path, fmt="tiff", output_file=filename, grayscale=True)` 
On cmd: run `pdftocairo -tiff sample.pdf` .

**Expected behavior**
Convert all pdfpages to tiff.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python: 3.9
 - Poppler: 21.03

**Additional context**
I noticed an error "No display font for ArialUnicode" and I though it was the root cause. I tried to install Arial Unicode MS but issue still remained. I resolved the error by embedding the fonts on Acrobat Pro but pdf2cairo still converts one page. 
Converting PDF to other formats like png or ppm successfully converts all pages.

[sample.pdf](https://github.com/Belval/pdf2image/files/6876200/sample.pdf)

**Comment by arethis** [comment]
I'm having the same issue, same OS / software versions listed above.

**Comment by Belval** [comment]
To clarify, you were able to reproduce this issue when using `pdftocairo` directly? If so this needs to be addressed but you should probably open an issue with the maintainers of poppler. `pdf2image` is only a wrapper around that library.

Open an issue here: https://gitlab.freedesktop.org/poppler/poppler

However in the meantime I can add a warning or even an exception to make sure that people don't accidentally use the broken feature.

**Comment by arethis** [comment]
I also had the thought that perhaps it's an issue with `pdftocairo`, after getting a better understanding of how `pdf2image` works, and that is indeed the case, the same issue is produced when converting a PDF to a TIFF file by running `pdftocairo` directly. 

**To provide some additional information to anyone else encountering this issue:**
It appears to be an issue specific to Windows 10, or the version of Poppler that is currently available on Windows, **21.03** while the current version of Poppler is **21.08.** The current version of Poppler works correctly on a base system install on Arch Linux (Release 2021.08.01)

The respective projects used to create the Windows binaries for Poppler (see below) are behind by several versions, and it's unclear where these projects are at in regards to being up to date with the current version of Poppler. 

**Poppler Windows Repos:** 
https://github.com/oschwartz10612/poppler-windows
https://github.com/conda-forge/poppler-feedstock

**Comment by frederick0291** [comment]
Opened an issue in gitlab: https://gitlab.freedesktop.org/poppler/poppler/-/issues/1112

As per the maintainer, pdftocairo is working for him.
This might be an issue in the version (21.03) we are using?

**Comment by Belval** [comment]
No luck, it seems like the feedstock is stuck on some odd compilation issue, will update the issue as we get more information.

**Comment by frederick0291** [comment]
Hi everyone.

I downloaded the latest windows release: poppler-21.08.0 from https://github.com/oschwartz10612/poppler-windows/releases/tag/v21.08.0 and tried testing again. Still converts only the first page. Raised the issue on the main poppler repo in gitlab and they said that it was working properly on their end. 

Tried adding first and last page with -f and -l options.
Tried using -e and -o options.
All of the above converted only the first page of the series.

I will try using the one in gitlab. I am not sure where the issue is coming from. It might be silently failing after the first page.

**Comment by frederick0291** [comment]
Let me know if I need to close this issue as it is an issue coming from the poppler-windows version.

**Comment by Belval** [comment]
I think it's ok to leave it open for now as we don't have a proper resolution and I would like to keep track of the issue. Make sure to report back if you find a solution.

**Comment by frederick0291** [comment]
Hi @Belval  I think the maintainers of `poppler-feedstock` found the cause of this issue. I will be requesting an update from `poppler-windows` to see if it fixes problem. 
https://github.com/conda-forge/poppler-feedstock/issues/111

**Comment by frederick0291** [comment]
Confirming that the issue has been fixed with the new update on `poppler-windows`
pdftocairo now converts all pages to `tiff`. Thanks!
