### ISSUE TITLE
When trying to convert pdf FORM it does not show checkboxes in image.

### ISSUE THREAD

**Issue by jehato47** [Belval/pdf2image#213]
**When trying to convert pdf FORM it does not show checkboxes in image.**

**To Reproduce**
[RFC-36.pdf](https://github.com/Belval/pdf2image/files/7083369/RFC-36.pdf)

Here is the sample pdf file.
If you try to convert it to images it will not show checkboxes in image.

Image of the pdf :
![output](https://user-images.githubusercontent.com/45170719/131491718-20e58140-8e2a-41da-bd6c-64fdcb42d457.jpg)

**Comment by Belval** [comment]
This is weird, I just tested it and I can confirm that bounding boxes do show up:

![out](https://user-images.githubusercontent.com/5399488/131503644-6f9716d2-3ab3-44b9-91ef-724258c22278.jpg)

What's your OS? I am on OS X with pdftoppm v20.12.1

**Comment by Belval** [comment]
Try to convert it manually with `pdftoppm -r 300 -jpeg your_file.pdf out` and see if there are any warnings. Since the installation on Windows is not handled by a package manager it is not uncommon to have missing packages which cause `pdf2image` to fail silently.

**Comment by jehato47** [comment]
Can you try it for this file:
[output.pdf](https://github.com/Belval/pdf2image/files/7084263/output.pdf)
