### ISSUE TITLE
Multi-threading doesn't work on AWS Lambda!

### ISSUE THREAD

**Issue by MohdImran001** [Belval/pdf2image#216]
**Describe the bug**
I am running pdf2image as a function on AWS Lambda. For testing purposes, let's use the following 100-page pdf.
[impatient-js-preview-book-1-100.pdf](https://github.com/Belval/pdf2image/files/7178084/impatient-js-preview-book-1-100.pdf). 

It is taking approx 10 seconds without multi-threading to convert the pdf into images. Even with multithreading, pdf2image takes 10 seconds on AWS Lambda, 

whereas on my personal computer (running Ubuntu 20.04) it takes `10 seconds without multithreading` and `5 seconds with multithreading on 4 threads`.

![100](https://user-images.githubusercontent.com/42844688/133621428-a9d224c2-c801-4b7f-9e22-f83c37ffdeda.png). 

I am using the following code.
```
    # Start converting PDF into JPEG Images
    app.log.info('Making images!')
    images = None
    with tempfile.TemporaryDirectory() as path:
        images = convert_from_bytes(
            pdf_file_bytes,
            dpi=300, 
            fmt=FMT, 
            thread_count=4,
            output_folder=path,
            jpegopt={"quality": 100, "optimize": False, "progressive": False},
            poppler_path='/var/task/lib/poppler_binaries/'
        )
    app.log.info('Images are ready!')
```

**Expected behavior**
pdf2image multi-threading should work on amazon lambda.

**Comment by Belval** [comment]
Well there are a lot of factors that could explain this from the top of my head here are the two main ones:

- Does your instance type have more than one thread?
- Are your pages very big which could cause an I/O bottleneck?

**Comment by MohdImran001** [comment]
Hi @Belval,
Thank you for your reply. The PDFs that we will be processing will not exceed 100 pages. I also tried this with a 50 page PDF which contains only text without any images, but still, the multithreading didn't work.  I am new to AWS Lambda, can you suggest to me the changes I need to make in the AWS Lambda environment to make multithreading work in pdf2image?

**Comment by MohdImran001** [comment]
Need to allocate at least `6GB` of RAM on `AWS Lambda` for multithreading to work.
