### ISSUE TITLE
Missing fonts with no error message

### ISSUE THREAD

**Issue by somnathnirakari** [Belval/pdf2image#217]
**Describe the bug**
I am trying to convert a pdf page to jpeg using pdf2image's convert_from_bytes function. The jpeg is generated but all the text as displayed as square boxes. I referred to https://github.com/Belval/pdf2image/issues/107 and used the pdftoppm tool as follows - 

`pdftoppm -r 300 image.pdf out -jpeg `

There is no error message displayed and the jpeg is generated with no text (square boxes)

When I open the pdf with preview tool on mac and then export the pdf as jpeg, I get the expected result with all the text displayed in the correct font. This suggests to me that the fonts are available but pdftoppm is not able to pick them up .

**To Reproduce**

`pdftoppm -r 300 image.pdf out -jpeg `

**Expected behavior**
A jpeg should be generated which should be a copy of the pdf page

**Desktop (please complete the following information):**
 - OS: [macOS Mojave]
 - Version [10.14.6]
-  pdftoppm version 21.09.0

**Additional context**
Please use the attached pdf for testing . I am also attaching the resulting jpeg for your reference
[image.pdf](https://github.com/Belval/pdf2image/files/7224384/image.pdf)
![out-1](https://user-images.githubusercontent.com/785031/134646446-ba24823a-aec0-4a82-8470-2b5702f497db.jpg)

**Comment by Belval** [comment]
Maybe this could raise a warning? I am wary of raising exceptions as it can be considered a breaking change.

**Comment by somnathnirakari** [comment]
The output of that command is no errors, no warnings. completes successfully. 
I was going by issue 107 in which you mentioned that a missing font would be logged.

Do you have any pointers how I could move further to debug this issue?

**Comment by Belval** [comment]
Unfortunately I don't and this seems like a `pdftoppm` bug that you can raise with the maintainers here: https://gitlab.freedesktop.org/poppler/poppler

From the pdf2image side if there is not warning raised then this is a transparent failure and I can't catch it.
