### ISSUE TITLE
Render page result is more drak then origin pdf?

### ISSUE THREAD

**Issue by frideal** [Belval/pdf2image#218]
```
convert_from_path(inputfilepath, 150, outputfolderpath ,fmt="PNG",output_file=outputfilename,size=(None,1080),thread_count=10)
```

i use convert_from_path to render each page to png files.but i find render result is more drak then origin pdf
**look at the camel and bull**

render result:
![image](https://user-images.githubusercontent.com/3777883/135382731-ff2192f6-7415-4cc4-873a-dab487e910ef.png)

origin pdf look in Adobe Acrobat Reader DC(32bit)
![image](https://user-images.githubusercontent.com/3777883/135382833-75533a24-d366-4f26-a045-201c3748108d.png)

origin:
![image](https://user-images.githubusercontent.com/3777883/135383581-2f50296b-3a66-46ed-abe4-0f627fc0354b.png)

pdf2image render result:
![image](https://user-images.githubusercontent.com/3777883/135383616-4c2bb93e-aa15-4299-b343-734a3660e615.png)

**Comment by Belval** [comment]
@mara004 response might be one thing, but you can also clearly see that pdftoppm is smoothing the output whereas Adobe is not.

Unfortunately `pdf2image` is just a wrapper around `pdftoppm` so I don't think anything can be done on my side :(
