### ISSUE TITLE
how to change the output image file name?

### ISSUE THREAD

**Issue by 3y3y3y** [Belval/pdf2image#22]
Hello! I am using your pdf2image and I find it a little bit uncomfortable that the file name of output image is kind of difficult to read and identify. Where can I find the place to modify the output file format? 
Thank you very much!

**Comment by Belval** [comment]
I am not quite sure why you'd want to manipulate the images, in practice, convert_from_path/convert_from_bytes will return a list of PIL image objects and you can save them wherever you want under the name convention you'd prefer.

The filename of the output images in the output folder is there to allow multithreading and prevent collision with pre-existing files in the same folder it might lead to unexpected behavior if such freedom was given in the filenames.

Please tell me if this explanation is satisfactory for you.

**Comment by Belval** [comment]
Closing for lack of response.
