### ISSUE TITLE
ImportError: No module named pdf2image with OSX and Python 2.7.18

### ISSUE THREAD

**Issue by sev7enITA** [Belval/pdf2image#225]
Hello,
I followed step by step the installation suggestions to setup the pdf2image module on my OSX installation built by using as most brew but I have always the same error with or without IDE: module not found.

I have python 2.7.18 and poppler installed properly.

I have no idea how to fix it...

**Comment by Belval** [comment]
pdf2image does not support Python 2.7, only +3.5.
