### ISSUE TITLE
wrong font and crop text

### ISSUE THREAD

**Issue by LCMA7** [Belval/pdf2image#229]
I am converting my PDF into image with `convert_from_path` from `pdf2image `library.

My issue is that the font in the image is not the good one and also that some text is missing (the adress in the bottom).

PDF : 
![Ok1MT](https://user-images.githubusercontent.com/85179628/152353964-92300c42-b87c-4c7f-b761-b6a364aa046a.png)

Image :
![mMFez](https://user-images.githubusercontent.com/85179628/152353991-cfb690f1-e849-44de-b137-b8d88a798f04.png)

So :
- Why is my text cropped ?
- How can I add the font to pdf2library ?

**Comment by gdabhishek** [comment]
Solved this font issue by installing 

`apt-get install fonts-liberation2`

**Comment by Belval** [comment]
Thank you for following up! I'll go ahead and close the issue.
