### ISSUE TITLE
pdf2image 1.16.1: Import error on Windows: No module named 'posix'

### ISSUE THREAD

**Issue by bladerail** [Belval/pdf2image#249]
**Describe the bug**
Import error on Windows:  No module named 'posix'

The posix module does not come built-in with Python on the Windows OS. Version 1.16.0 works ok, but version 1.16.1 does not.

**To Reproduce**
1. `pip install pdf2image==1.16.1`
2. 
```python
from pdf2image import convert_from_path
```
3. Run the above script
4. Get `ModuleNotFoundError: No module named 'posix'`

**Expected behavior**
Import should work as intended

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python 3.9.13 installed via Anaconda
 - pdf2image version 1.16.1

**Additional context**
`pip install pdf2image==1.16.0` works correctly because the change to `pdf2image/pdf2image.py` line 8 was done in 1.16.1.

**Comment by Belval** [comment]
Looking into it.

**Comment by Belval** [comment]
Fixed in 1.16.2, thank you for raising this issue. I will pull the previous package from PyPI.
