### ISSUE TITLE
[Errno 2] No such file or directory: 'pdfinfo'

### ISSUE THREAD

**Issue by DJDrennan** [Belval/pdf2image#25]
Why is it looking for pdfinfo ? what is it supposed to have in it ? where should it be ?

**Comment by Belval** [comment]
pdfinfo is part of the poppler-utils package. It is used to count how many pages there are in the PDF before processing.

Ultimately, this information is needed mostly for multiprocessing and limiting the number of pages processed.

I can assist you in installing pdfinfo but I would need your OS first.

**Comment by DJDrennan** [comment]
I installed poppler, but I'm still getting an error... what do I try next ?


In [1]: from pdf2image import *

In [2]: images = convert_from_path('/home/dianad/testing/UDC-000280.pdf', output_folder='/home/dianad/testing', first_page=1, 
   ...: last_page=1, fmt='jpg')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/.conda/envs/dc/lib/python3.5/site-packages/pdf2image/pdf2image.py in __page_count(pdf_path, userpw)
    162         # This will throw if we are unable to get page count
--> 163         return int(re.search(r'Pages:\s+(\d+)', out.decode("utf8", "ignore")).group(1))
    164     except:

AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
<ipython-input-2-39f7ce035a68> in <module>()
----> 1 images = convert_from_path('/home/dianad/testing/UDC-000280.pdf', output_folder='/home/dianad/testing', first_page=1, last_page=1, fmt='jpg')

~/.conda/envs/dc/lib/python3.5/site-packages/pdf2image/pdf2image.py in convert_from_path(pdf_path, dpi, output_folder, first_page, last_page, fmt, thread_count, userpw)
     27     """
     28 
---> 29     page_count = __page_count(pdf_path, userpw)
     30 
     31     if thread_count < 1:

~/.conda/envs/dc/lib/python3.5/site-packages/pdf2image/pdf2image.py in __page_count(pdf_path, userpw)
    163         return int(re.search(r'Pages:\s+(\d+)', out.decode("utf8", "ignore")).group(1))
    164     except:
--> 165         raise Exception('Unable to get page count.')
    166 
    167 def __load_from_output_folder(output_folder, uid):

Exception: Unable to get page count.

In [3]:

**Comment by Belval** [comment]
If you installed poppler the error is somewhere else. First check is you can call pdfinfo on your pdf.

`pdfinfo /home/dianad/testing/UDC-000280.pdf`

Also, if you could provide me with a sample so I can reproduce the issue on my side it would be helpful.

**Comment by zevgriner** [comment]
A friend has the same problem.
When the package is initialized, for Windows, at least, please check the "path" to make sure poppler  exists in the path. Otherwise, the package generates a FileNotFound error when pdfinfo can't be found, without specifying which file can't be found.

**Comment by Belval** [comment]
@zevgriner do you consider this an acceptable solution: https://github.com/Belval/pdf2image/commit/a31453f1b22e658499b2a8675cbe37d5da3777a3? 

I don't want to check for pdfinfo/pdftoppm existence in PATH because that would add an overhead for everyone who configured their installation correctly.

As for adding a parameter, this is mostly a problem for Windows users with a bad configuration, it wouldn't make much sense to add it. Instead, I believe we should encourage people in the "good" direction of setting up poppler properly.

Please share your thoughts on the matter.

**Comment by gauravv7** [comment]
confirming, this issue also occurs for ubuntu 14.04 LTS x64.
solution: sudo apt-get install -y poppler-utils
but somehow installation didn't worked for the first time. second install over the first without any uninstallation solves for me.

**Comment by Belval** [comment]
Added Ubuntu 16.04+ mention in https://github.com/Belval/pdf2image/commit/2f8b627fe7e29947146f5a6783888946801f5634

**Comment by guanshuicheng** [comment]
> confirming, this issue also occurs for ubuntu 14.04 LTS x64.
> solution: sudo apt-get install -y poppler-utils
> but somehow installation didn't worked for the first time. second install over the first without any uninstallation solves for me.

Thank you very much,it works for me

**Comment by nemadaliev** [comment]
Thank you, did work for me too.

**Comment by SantiMNV** [comment]
Thanks! Works for me too
