### ISSUE TITLE
pdf2image poppler error in Linux

### ISSUE THREAD

**Issue by arjun251** [Belval/pdf2image#252]
We are trying to install pdf2image in the Azure cloud Linux environment. We are struggling with the below error on installing Poppler which is one of the dependencies for pdf2image. 

I am really glad and thankful if you can help me with the workaround solution.

apt install build-essential libpoppler-cpp-dev pkg-config python3-dev

Reading package lists... Done

Building dependency tree      

Reading state information... Done

The following additional packages will be installed:

  dh-python dpkg-dev fakeroot g++ g++-8 gcc gcc-8 libalgorithm-diff-perl libalgorithm-diff-xs-perl libalgorithm-merge-perl libasan5 libatomic1 libcc1-0 libdpkg-perl

  libexpat1-dev libfakeroot libfile-fcntllock-perl libgcc-8-dev libitm1 liblocale-gettext-perl liblsan0 libmpx2 libopenjp2-7 libpoppler-cpp0v5 libpoppler-dev

  libpoppler82 libpython3-dev libpython3.7 libpython3.7-dev libquadmath0 libstdc++-8-dev libtsan0 libubsan1 make patch poppler-data python3-distutils python3-lib2to3

  python3.7-dev

Suggested packages:

  debian-keyring g++-multilib g++-8-multilib gcc-8-doc libstdc++6-8-dbg gcc-multilib autoconf automake libtool flex bison gdb gcc-doc gcc-8-multilib gcc-8-locales

  libgcc1-dbg libgomp1-dbg libitm1-dbg libatomic1-dbg libasan5-dbg liblsan0-dbg libtsan0-dbg libubsan1-dbg libmpx2-dbg libquadmath0-dbg git bzr libstdc++-8-doc

  make-doc ed diffutils-doc poppler-utils ghostscript fonts-japanese-mincho | fonts-ipafont-mincho fonts-japanese-gothic | fonts-ipafont-gothic fonts-arphic-ukai

  fonts-arphic-uming fonts-nanum

The following NEW packages will be installed:

  build-essential dh-python dpkg-dev fakeroot g++ g++-8 gcc gcc-8 libalgorithm-diff-perl libalgorithm-diff-xs-perl libalgorithm-merge-perl libasan5 libatomic1 libcc1-0

  libdpkg-perl libexpat1-dev libfakeroot libfile-fcntllock-perl libgcc-8-dev libitm1 liblocale-gettext-perl liblsan0 libmpx2 libopenjp2-7 libpoppler-cpp-dev

  libpoppler-cpp0v5 libpoppler-dev libpoppler82 libpython3-dev libpython3.7 libpython3.7-dev libquadmath0 libstdc++-8-dev libtsan0 libubsan1 make patch pkg-config

  poppler-data python3-dev python3-distutils python3-lib2to3 python3.7-dev

0 upgraded, 43 newly installed, 0 to remove and 1 not upgraded.

Need to get 82.3 MB of archives.

After this operation, 208 MB of additional disk space will be used.

Do you want to continue? [Y/n] Y

Err:1 http://deb.debian.org/debian buster/main amd64 liblocale-gettext-perl amd64 1.07-3+b4

  503  Service Unavailable [IP: 146.75.30.132 80]

Err:2 http://deb.debian.org/debian buster/main amd64 poppler-data all 0.4.9-2

  503  Service Unavailable [IP: 146.75.30.132 80]

Err:3 http://deb.debian.org/debian buster/main amd64 libcc1-0 amd64 8.3.0-6

  503  Service Unavailable [IP: 146.75.30.132 80]

Err:4 http://deb.debian.org/debian buster/main amd64 libitm1 amd64 8.3.0-6

  503  Service Unavailable [IP: 146.75.30.132 80]

Err:5 http://deb.debian.org/debian buster/main amd64 libatomic1 amd64 8.3.0-6

  503  Service Unavailable [IP: 146.75.30.132 80]

Err:6 http://deb.debian.org/debian buster/main amd64 libasan5 amd64 8.3.0-6

  503  Service Unavailable [IP: 146.75.30.132 80]

Err:7 http://deb.debian.org/debian buster/main amd64 liblsan0 amd64 8.3.0-6

  503  Service Unavailable [IP: 146.75.30.132 80]

Err:8 http://deb.debian.org/debian buster/main amd64 libtsan0 amd64 8.3.0-6

  503  Service Unavailable [IP: 146.75.30.132 80]

Err:9 http://deb.debian.org/debian buster/main amd64 libubsan1 amd64 8.3.0-6

  503  Service Unavailable [IP: 146.75.30.132 80]

Err:10 http://deb.debian.org/debian buster/main amd64 libmpx2 amd64 8.3.0-6

  503  Service Unavailable [IP: 146.75.30.132 80]

Err:11 http://deb.debian.org/debian buster/main amd64 libquadmath0 amd64 8.3.0-6

  503  Service Unavailable [IP: 146.75.30.132 80]

Err:12 http://deb.debian.org/debian buster/main amd64 libgcc-8-dev amd64 8.3.0-6

  503  Service Unavailable [IP: 146.75.30.132 80]

Err:13 http://deb.debian.org/debian buster/main amd64 gcc-8 amd64 8.3.0-6

  503  Service Unavailable [IP: 146.75.30.132 80]

Err:14 http://deb.debian.org/debian buster/main amd64 gcc amd64 4:8.3.0-1

  503  Service Unavailable [IP: 146.75.30.132 80]

Err:15 http://deb.debian.org/debian buster/main amd64 libstdc++-8-dev amd64 8.3.0-6

  503  Service Unavailable [IP: 146.75.30.132 80]

Err:16 http://deb.debian.org/debian buster/main amd64 g++-8 amd64 8.3.0-6

  503  Service Unavailable [IP: 146.75.30.132 80]

Err:17 http://deb.debian.org/debian buster/main amd64 g++ amd64 4:8.3.0-1

  503  Service Unavailable [IP: 146.75.30.132 80]

Err:18 http://deb.debian.org/debian buster/main amd64 make amd64 4.2.1-1.2

  503  Service Unavailable [IP: 146.75.30.132 80]

Ign:19 http://deb.debian.org/debian buster/main amd64 libdpkg-perl all 1.19.8

Ign:20 http://deb.debian.org/debian buster/main amd64 patch amd64 2.7.6-3+deb10u1

Ign:21 http://deb.debian.org/debian buster/main amd64 dpkg-dev all 1.19.8

Err:22 http://deb.debian.org/debian buster/main amd64 build-essential amd64 12.6

  503  Service Unavailable [IP: 146.75.30.132 80]

Err:23 http://deb.debian.org/debian buster/main amd64 python3-lib2to3 all 3.7.3-1

  503  Service Unavailable [IP: 146.75.30.132 80]

Err:24 http://deb.debian.org/debian buster/main amd64 python3-distutils all 3.7.3-1

  503  Service Unavailable [IP: 146.75.30.132 80]

Err:25 http://deb.debian.org/debian buster/main amd64 dh-python all 3.20190308

  503  Service Unavailable [IP: 146.75.30.132 80]

Err:26 http://deb.debian.org/debian buster/main amd64 libfakeroot amd64 1.23-1

  503  Service Unavailable [IP: 146.75.30.132 80]

Err:27 http://deb.debian.org/debian buster/main amd64 fakeroot amd64 1.23-1

  503  Service Unavailable [IP: 146.75.30.132 80]

Err:28 http://deb.debian.org/debian buster/main amd64 libalgorithm-diff-perl all 1.19.03-2

  503  Service Unavailable [IP: 146.75.30.132 80]

Err:29 http://deb.debian.org/debian buster/main amd64 libalgorithm-diff-xs-perl amd64 0.04-5+b1

  503  Service Unavailable [IP: 146.75.30.132 80]

Err:30 http://deb.debian.org/debian buster/main amd64 libalgorithm-merge-perl all 0.08-3

  503  Service Unavailable [IP: 146.75.30.132 80]

Err:31 http://deb.debian.org/debian-security buster/updates/main amd64 libexpat1-dev amd64 2.2.6-2+deb10u5

  503  Service Unavailable [IP: 146.75.30.132 80]

Err:32 http://deb.debian.org/debian buster/main amd64 libfile-fcntllock-perl amd64 0.22-3+b5

  503  Service Unavailable [IP: 146.75.30.132 80]

Ign:33 http://deb.debian.org/debian buster/main amd64 libopenjp2-7 amd64 2.3.0-2+deb10u2

Err:34 http://deb.debian.org/debian-security buster/updates/main amd64 libpoppler82 amd64 0.71.0-5+deb10u1

  503  Service Unavailable [IP: 146.75.30.132 80]

Err:35 http://deb.debian.org/debian-security buster/updates/main amd64 libpoppler-cpp0v5 amd64 0.71.0-5+deb10u1

  503  Service Unavailable [IP: 146.75.30.132 80]

Err:36 http://deb.debian.org/debian-security buster/updates/main amd64 libpoppler-dev amd64 0.71.0-5+deb10u1

  503  Service Unavailable [IP: 146.75.30.132 80]

Err:37 http://deb.debian.org/debian-security buster/updates/main amd64 libpoppler-cpp-dev amd64 0.71.0-5+deb10u1

  503  Service Unavailable [IP: 146.75.30.132 80]

Err:38 http://deb.debian.org/debian buster/main amd64 libpython3.7 amd64 3.7.3-2+deb10u3

  503  Service Unavailable [IP: 146.75.30.132 80]

Err:39 http://deb.debian.org/debian buster/main amd64 libpython3.7-dev amd64 3.7.3-2+deb10u3

  503  Service Unavailable [IP: 146.75.30.132 80]

Err:40 http://deb.debian.org/debian buster/main amd64 libpython3-dev amd64 3.7.3-1

  503  Service Unavailable [IP: 146.75.30.132 80]

Err:41 http://deb.debian.org/debian buster/main amd64 pkg-config amd64 0.29-6

  503  Service Unavailable [IP: 146.75.30.132 80]

Err:42 http://deb.debian.org/debian buster/main amd64 python3.7-dev amd64 3.7.3-2+deb10u3

  503  Service Unavailable [IP: 146.75.30.132 80]

Err:43 http://deb.debian.org/debian buster/main amd64 python3-dev amd64 3.7.3-1

  503  Service Unavailable [IP: 146.75.30.132 80]

Err:19 http://deb.debian.org/debian buster/main amd64 libdpkg-perl all 1.19.8

  503  Service Unavailable [IP: 146.75.30.132 80]

Err:20 http://deb.debian.org/debian buster/main amd64 patch amd64 2.7.6-3+deb10u1

  503  Service Unavailable [IP: 146.75.30.132 80]

Err:21 http://deb.debian.org/debian buster/main amd64 dpkg-dev all 1.19.8

  503  Service Unavailable [IP: 146.75.30.132 80]

Err:33 http://deb.debian.org/debian buster/main amd64 libopenjp2-7 amd64 2.3.0-2+deb10u2

  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian/pool/main/libl/liblocale-gettext-perl/liblocale-gettext-perl_1.07-3+b4_amd64.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian/pool/main/p/poppler-data/poppler-data_0.4.9-2_all.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian/pool/main/g/gcc-8/libcc1-0_8.3.0-6_amd64.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian/pool/main/g/gcc-8/libitm1_8.3.0-6_amd64.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian/pool/main/g/gcc-8/libatomic1_8.3.0-6_amd64.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian/pool/main/g/gcc-8/libasan5_8.3.0-6_amd64.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian/pool/main/g/gcc-8/liblsan0_8.3.0-6_amd64.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian/pool/main/g/gcc-8/libtsan0_8.3.0-6_amd64.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian/pool/main/g/gcc-8/libubsan1_8.3.0-6_amd64.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian/pool/main/g/gcc-8/libmpx2_8.3.0-6_amd64.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian/pool/main/g/gcc-8/libquadmath0_8.3.0-6_amd64.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian/pool/main/g/gcc-8/libgcc-8-dev_8.3.0-6_amd64.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian/pool/main/g/gcc-8/gcc-8_8.3.0-6_amd64.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian/pool/main/g/gcc-defaults/gcc_8.3.0-1_amd64.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian/pool/main/g/gcc-8/libstdc++-8-dev_8.3.0-6_amd64.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian/pool/main/g/gcc-8/g++-8_8.3.0-6_amd64.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian/pool/main/g/gcc-defaults/g++_8.3.0-1_amd64.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian/pool/main/m/make-dfsg/make_4.2.1-1.2_amd64.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian-security/pool/updates/main/d/dpkg/libdpkg-perl_1.19.8_all.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian-security/pool/updates/main/p/patch/patch_2.7.6-3+deb10u1_amd64.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian-security/pool/updates/main/d/dpkg/dpkg-dev_1.19.8_all.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian/pool/main/b/build-essential/build-essential_12.6_amd64.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian/pool/main/p/python3-stdlib-extensions/python3-lib2to3_3.7.3-1_all.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian/pool/main/p/python3-stdlib-extensions/python3-distutils_3.7.3-1_all.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian/pool/main/d/dh-python/dh-python_3.20190308_all.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian/pool/main/f/fakeroot/libfakeroot_1.23-1_amd64.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian/pool/main/f/fakeroot/fakeroot_1.23-1_amd64.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian/pool/main/liba/libalgorithm-diff-perl/libalgorithm-diff-perl_1.19.03-2_all.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian/pool/main/liba/libalgorithm-diff-xs-perl/libalgorithm-diff-xs-perl_0.04-5+b1_amd64.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian/pool/main/liba/libalgorithm-merge-perl/libalgorithm-merge-perl_0.08-3_all.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian-security/pool/updates/main/e/expat/libexpat1-dev_2.2.6-2+deb10u5_amd64.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian/pool/main/libf/libfile-fcntllock-perl/libfile-fcntllock-perl_0.22-3+b5_amd64.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian-security/pool/updates/main/o/openjpeg2/libopenjp2-7_2.3.0-2+deb10u2_amd64.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian-security/pool/updates/main/p/poppler/libpoppler82_0.71.0-5+deb10u1_amd64.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian-security/pool/updates/main/p/poppler/libpoppler-cpp0v5_0.71.0-5+deb10u1_amd64.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian-security/pool/updates/main/p/poppler/libpoppler-dev_0.71.0-5+deb10u1_amd64.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian-security/pool/updates/main/p/poppler/libpoppler-cpp-dev_0.71.0-5+deb10u1_amd64.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian/pool/main/p/python3.7/libpython3.7_3.7.3-2+deb10u3_amd64.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian/pool/main/p/python3.7/libpython3.7-dev_3.7.3-2+deb10u3_amd64.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian/pool/main/p/python3-defaults/libpython3-dev_3.7.3-1_amd64.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian/pool/main/p/pkg-config/pkg-config_0.29-6_amd64.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian/pool/main/p/python3.7/python3.7-dev_3.7.3-2+deb10u3_amd64.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Failed to fetch http://deb.debian.org/debian/pool/main/p/python3-defaults/python3-dev_3.7.3-1_amd64.deb  503  Service Unavailable [IP: 146.75.30.132 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by Belval** [comment]
This is unrelated to pdf2image. The debian mirror you are trying to fetch from is giving an error code. I would advise doing `sudo apt update` first to make sure your lists are up to date and attempt to install the packages again. If that doesn't work wait a bit (~1hr) and it should resolve itself.

If it still doesn't you could raise it with Azure.
