### ISSUE TITLE
Missing py.typed file

### ISSUE THREAD

**Issue by PedroPerpetua** [Belval/pdf2image#255]
Type annotations were added in commit aa6aee8bcd9da84a4f5b5dc1614fb6e200228d0d seem to be complete, but linters like MyPy still shoot out an error due to no `py.typed` file being present when installed trough pip.

More details can be found here: https://mypy.readthedocs.io/en/stable/running_mypy.html?highlight=py.typed#missing-library-stubs-or-py-typed-marker

Simply adding a `py.typed` file to the pip packaging should fix the issue.

**Comment by Belval** [comment]
I am unfamiliar with `py.typed`, but I don't see any reason to not add it. I'll see if I get around to doing it otherwise feel free to submit a PR.

**Comment by PedroPerpetua** [comment]
@Belval here's the relevant PEP: https://peps.python.org/pep-0561/#packaging-type-information

**Comment by PedroPerpetua** [comment]
PR opened: #256

**Comment by PedroPerpetua** [comment]
Closed with #256
