### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 70-76: ordinal not in range(128)

### ISSUE THREAD

**Issue by wiyan** [Belval/pdf2image#26]
there wil be a problem when the fileppath have chinese
![image](https://user-images.githubusercontent.com/3435046/44255894-13df3c00-a23a-11e8-9210-29e4e9dd2fd7.png)

**Comment by Belval** [comment]
Did setting the encoding explicitly solve your problem?

**Comment by Belval** [comment]
Closing for lack of response.

Feel free to reopen it if you experience this issue again.
