### ISSUE TITLE
Changing the name of the output file

### ISSUE THREAD

**Issue by rsomani95** [Belval/pdf2image#27]
This issue was raised before [here](https://github.com/Belval/pdf2image/issues/22), but got closed prematurely.

I wanted to know if there is any way that we can have control over the name of the output image. While I understand there are reasons why the filename is the way it is from your explanation in the previous issue, it would save me a lot of time and resources if I could change the output name. 

Thanks!

**Comment by Belval** [comment]
Would you mind describing your process? You can access the filename using `Image.filename` and every image has a `_X` suffix where X is the page number. 

Don't get me wrong, I am not completely closed to the idea, I simply have trouble picturing a legitimate scenario.

**Comment by rsomani95** [comment]
> Would you mind describing your process?

Sure, I'm working on a data visualisation project where I prepare the data in Python, run it using [Processing](http://processing.org/) on the Terminal, but in order to run it in headless mode, I need to [export it to PDF](https://processing.org/reference/libraries/pdf/index.html) as that's the only case where I can automate the process (I'm working on macOS, there are better solutions for Linux OS). I need to use `pdf2image` to convert these PDFs back to JPEGs as I'd like to put these together sequentially in a video editor. 
Thus, naming them correctly is crucial.


>You can access the filename using `Image.filename` and every image has a `_X` suffix where X is the page number.

Thank you. I realised I was making the silly error of accessing the list itself, and not the element of the list. 
Here's the code for anyone facing a similar issue:

`img = convert_from_path(pdf_path = proc_path[0], output_folder = out_path, fmt = 'jpg')
img.filename`  _#gives an error: 'list' object has no attribute 'filename'_
`img[0].filename`   does the trick.
