### ISSUE TITLE
How to embed image into html body?

### ISSUE THREAD

**Issue by Daniel-Li-Anomali** [Belval/pdf2image#28]
Hi so I am wanting to convert a pdf binary to a jpeg and then embed it into a html string to be push to our server. 
This is what I have so far:

` self.pdf_file  = Binary_pdf `
` images = convert_from_bytes(self.pdf_file, 200, fmt="jpg", thread_count=1)`
I then want to loop through the images and put them in my body string to be uploaded:

```
    images = images.reverse() 
    for image in images:
        body += <img src = <image binary?></img>
```

How to do this?

**Comment by Belval** [comment]
This question would be better asked on StackOverflow as it is not an issue with pdf2image. That being said, you want to do something like this:

```
import base64
from io import BytesIO

images = convert_from_bytes(...)
body = ""

for im in images:
    im_bytes = BytesIO()
    im.save(im_bytes, format='PNG')
    body += "<img src=" + base64.b64encode(im_bytes.getvalue()) + "></img> 
```

**Comment by Daniel-Li-Anomali** [comment]
> This question would be better asked on StackOverflow as it is not an issue with pdf2image. That being said, you want to do something like this:
> 
> ```
> import base64
> from io import BytesIO
> 
> images = convert_from_bytes(...)
> body = ""
> 
> for im in images:
>     im_bytes = BytesIO()
>     im.save(im_bytes, format='PNG')
>     body += "<img src=" + base64.b64encode(im_bytes.getvalue()) + "></img>"
> ```

I had to add 

> data:image/png;base64,

 to the body to get it to work. So the last line needs to be this:
`                    body += """<img src="data:image/png;base64,{}" width=50%>""".format(img_str)
`
