### ISSUE TITLE
Does not keep the order

### ISSUE THREAD

**Issue by mkal1375** [Belval/pdf2image#3]
your library Does not keep the order of pdf file.
when i save images by indexes.

```python
with tempfile.TemporaryDirectory() as path:
     images = convert_from_path('/Users/mkal/Desktop/sample/sample.pdf', output_folder=path)
     for image in images:
         image.save("{}.jpg".format(images.index(image)),"JPEG")
```
The pages are not in order ...  🤔

**Comment by Belval** [comment]
That's definitely an issue, I'll try to reproduce it and push a fix today.

Do you know if it does the same thing when you don't give it an output path?

**Comment by Belval** [comment]
Issue successfully reproduced, should be pushing a fix in 30 mins.

**Comment by Belval** [comment]
Should be fix. A new package was deployed (0.1.6) that address the issue. I will await your confirmation before closing.

**Comment by mkal1375** [comment]
fixed! Thank you very much.

**Comment by nineliejasongu1122** [comment]
Hi the same error occurs when I try to convert pdf to image: 

`    with TemporaryDirectory() as tempdir:
        if platform.system() == "Windows":
            convert_from_path(pdf_file, dpi, poppler_path=path_to_poppler_exe, output_folder=tempdir, fmt='jpg')
        else:
            convert_from_path(pdf_file, dpi, output_folder=tempdir, fmt='jpg')`
Please assist with this issue. Thank you so much!
