### ISSUE TITLE
The library doesn't work for pdfs with large number of pages

### ISSUE THREAD

**Issue by vinayakkailas** [Belval/pdf2image#31]
I tried converting each page of a pdf to JPEG images. The conversion is not happening. PDF is having 3248 pages. No error being thrown but the execution went to an idle state

**Comment by Belval** [comment]
From the top of my head, at that size, you want to make sure that your are using an output_folder and that your format is not ppm.

I'll make a test case on my side as I have never tested more than 500 pages.

**Comment by Belval** [comment]
Just tested with a 2368 pages PDF. If you allow for enough open file handle it does not seem to cause any issue on Ubuntu Server 18.04.

**Comment by vinayakkailas** [comment]
please may i know, what change i should make in my linux system to allow enough file handle?

**Comment by Belval** [comment]
On my system, I was able to simply `ulimit -n 70000` to make it work.

You might want to make sure that this will persist between reboots.

**Comment by vinayakkailas** [comment]
I made it to 70000 as you said...still no chance

**Comment by munikarmanish** [comment]
I'm getting this issue even with a PDF with less than 200 pages (less than 500 KiB).

@Belval is it possible to return the list of images as a generator instead (if that would solve this issue)?

**Comment by Belval** [comment]
If you just want a specific page there are the `first` and `last` parameters. As for the output_folder, you really want to use a `tempfile.NamedDirectory` to ensure that the files get cleaned up afterwards.

**Comment by Belval** [comment]
As for why the generated images are not handled by pdf2image, that's because of how Pillow handles images. You see, when you do `Image.open()`, the image is just lazy-loaded until you actually use it. If pdf2image cleaned the temp directory, the image converted would become unusable.

**Comment by munikarmanish** [comment]
Ah, I see. No problem. I used `tempfile.TemporaryDirectory` as you suggested and it's working fine. :+1: :smiley:

**Comment by Belval** [comment]
Unfortunately no, as pdftoppm returns all pages at once and this is just a thin wrapper with added multithreading.

**Comment by maheshk3176** [comment]
I am unable to open the pdf with 2nd password.

**Comment by shang6107** [comment]
I just try to convert a pdf file less than 50 pages to jpg, there are no jpg files output also,  but png. what should i do

**Comment by shang6107** [comment]
By the way, pdf2image's version is 1.6, and what version of poppler is better?

**Comment by Belval** [comment]
This issue is now pretty old and a lot have changed since it was originally opened. Feel free to open another issue if you still have issues with PDFs that have a lot of pages.

**Comment by levkany** [comment]
anyone managed to solve the issue with large pdfs with a lot of pages?
i am trying to loop each page so generator would be a good solution.

anyone figured it out?
