### ISSUE TITLE
Cannot delete *.ppm files after process

### ISSUE THREAD

**Issue by nguyenhuyanhh** [Belval/pdf2image#32]
**Describe the issue**
I cannot seem to delete *.ppm files after running the pdf2image. The code is taken from a test suite, where I intend to delete all *.ppm and *.jpg files after test execution.

**Steps to reproduce**
Test script:
```
...
    @classmethod
    def tearDownClass(cls):
        files_to_delete = [x for x in os.listdir(
            DATA_DIR) if os.path.splitext(x)[1] in ['.ppm', '.jpg']]
        for x in files_to_delete:
           os.remove(os.path.join(DATA_DIR, x))
...
```
Error log:
```
=================================== ERRORS ====================================
__________ ERROR at teardown of TestPDFComparer.test_is_both_invalid __________

cls = <class 'test.test_pdf.TestPDFComparer'>

    @classmethod
    def tearDownClass(cls):
        files_to_delete = [x for x in os.listdir(
            DATA_DIR) if os.path.splitext(x)[1] in ['.ppm', '.jpg']]
        for x in files_to_delete:
>           os.remove(os.path.join(DATA_DIR, x))
E           PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'I:\\pdf-compare\\test\\test_data\\2a9ae9eb-6edd-40da-b46f-b49fa1e0e459-1.ppm'

test\test_pdf.py:131: PermissionError
===================== 17 passed, 1 error in 2.15 seconds ======================
```

**Desktop environment:**
 - OS: Windows 7
 - Python: 3.6.4 (Anaconda)

**Comment by Belval** [comment]
First, thank you for using the provided issue template, it helps a lot.

I have to admit that I doubt this issue is related to pdf2image, Does it still happen if you generate jpeg instead?

**Comment by nguyenhuyanhh** [comment]
Anyway, I think I figured it out - some of the images returned by pdf2image are not used by the test suite, leaving their file handles opened. Manually closing the images in `tearDownClass()` seems to solve the issue.

Thanks a lot for the nice library!

**Comment by Belval** [comment]
Glad you got it sorted out!
