### ISSUE TITLE
pdf2image outputs blank image when the orientation of pages in PDF is alternating 

### ISSUE THREAD

**Issue by gskishan004** [Belval/pdf2image#33]
**Describe the bug**
I get a blank output image when the pdf contains pages which have different orientations.
For instance: 
If the pages are in portrait orientation till page 6 and the code encounters landscape orientation from page 7 onward, then the pages from 7 to 8 will be blank.

**To Reproduce**
1. Take a pdf while have combination of pages in two different orientation, say 1-6 in portrait and 7-10 in landscape
2. Run the program with fmt parameter set as  "jpg" and output_folder as "image"
3. You will see that pages 7 and 8 will be blank.

**Expected behavior**
Images to have content similar to pdf

**Desktop (please complete the following information):**
 - Windows
 - Python 3.5.5

**Comment by Belval** [comment]
I tried to reproduce your issue with a pdf similar to what you described, but the results were consistent with what is expected.

Can you provide a test case?

**Comment by Belval** [comment]
Closing due to lack of response. Feel free to reopen if this is still an issue.
