### ISSUE TITLE
pdf2image is not trivially usable in AWS Lambda

### ISSUE THREAD

**Issue by AndreaAdvanon** [Belval/pdf2image#36]
**Describe the bug**
I'm trying to use this library in an AWS Lambda.
```
Exception: Unable to get page count. Is poppler installed and in PATH?
```

**To Reproduce**
1. Create a lambda in python that uses `pdf2image`
2. Run it

**Expected behavior**
Would be nice to have an official guide on how to make it work, as I'm still trying to figure out how to include it. I'm no python expert but I guess shipping the binary directly would be the best.

**Comment by Belval** [comment]
I must confess that I have little experience with AWS Lambda but I like the idea of having official documentation on how to deploy on cloud providers.

I have been working on another repository called [pdf2image-as-a-service](https://github.com/Belval/pdf2image-as-a-service) while my current approach is to bundle the application in a docker container and deploy it on ECS (on AWS), I could add a how-to with AWS lambda.

In the meantime, if you figure it out please reply here as it could be used as a starting point for others.

**Comment by AndreaAdvanon** [comment]
@Belval unfortunately I didn't have enough time to sort this through so I ended up ditching AWS Lambda for this small project.

I would love to see support for Lambda though. If there were a straightforward way to use this library on Lambda I would move back to it.

**Comment by hinsley** [comment]
[Poppler](https://poppler.freedesktop.org/) is a dependency of pdf2image -- you'll have to install it and place it in your PATH (`export PATH="$PATH:/path/to/poppler"` or just install via Conda) before pdf2image will work.

**Comment by Belval** [comment]
Indeed, but have you succeeded in installing it? If you did I'd be very interested to read about it.

**Comment by Belval** [comment]
There is now an exhaustive example (with scripts to do it auto-magically) in https://github.com/Belval/pdf2image-as-a-service

If you have any problem with that example, feel free to open an issue on that repository.
