### ISSUE TITLE
Directory name or file name include number will throw a error

### ISSUE THREAD

**Issue by zxjbeijing2018** [Belval/pdf2image#47]
**Describe the bug**
Directory name or file name include number will throw a error

**To Reproduce**

**Expected behavior**
if the pdf file in the directory like below, will throw a error: 
the directory: digitalbook/pdf/temp/t/1/output.pdf or digitalbook/pdf/temp/t/1output.pdf
Unable to get page count. Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table

if the directory like this : digitalbook/pdf/temp/t/output.pdf. Will be OK.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.1
 - Version 1.4.0

**Additional context**

**Comment by Belval** [comment]
I was **not** able to reproduce the issue with the paths provided on Archlinux with version 1.4.0.

If you could provide a code sample and the PDF you used it would help a lot.

**Comment by zxjbeijing2018** [comment]
Attached please find the code file and pdf file. Please help me if there are any issues of using the package. Thank you very much. 


[pdf2image.txt](https://github.com/Belval/pdf2image/files/2847830/pdf2image.txt)
[output.pdf](https://github.com/Belval/pdf2image/files/2847833/output.pdf)

**Comment by Belval** [comment]
Hi there! Sorry for the delay, this issue definitely fell off my radar.

Even using the snippet provided and recreating your directory structure the PDF is successfully converted on Archlinux (which should be more or less equivalent to Ubuntu 18.04).

Since this was a month ago, were you able to solve your problem?

**Comment by Belval** [comment]
Glad you got it sorted out!
