### ISSUE TITLE
Unable to convert pdf to image using pdf2image

### ISSUE THREAD

**Issue by Kartik98qw** [Belval/pdf2image#48]
`def convert(files):
  pages = convert_from_path(files, 500)
  out_file="ConvertedToImage.jpg"	
  for page in pages:
     page.save(out_file, 'JPEG')
  return out_file`

Above is the code snippet of the function. I am getting a following error while converting the pdf to image: 
Traceback (most recent call last):
  File "C:\Users\DEll\AppData\Local\Programs\Python\Python36\lib\site-packages\pdf2image\pdf2image.py", line 190, in _page_count
    return int(re.search(r'Pages:\s+(\d+)', out.decode("utf8", "ignore")).group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "final.py", line 11, in <module>
    divide.send(in_file)
  File "C:\Users\DEll\Downloads\Interns Py\divide.py", line 123, in send
    toIm=convert(in_file)
  File "C:\Users\DEll\Downloads\Interns Py\divide.py", line 86, in convert
    pages = convert_from_path(files, 500)
  File "C:\Users\DEll\AppData\Local\Programs\Python\Python36\lib\site-packages\pdf2image\pdf2image.py", line 46, in convert_from_path
    page_count = _page_count(pdf_path, userpw)
  File "C:\Users\DEll\AppData\Local\Programs\Python\Python36\lib\site-packages\pdf2image\pdf2image.py", line 192, in _page_count
    raise PDFPageCountError('Unable to get page count. %s' % err.decode("utf8", "ignore"))
pdf2image.exceptions.PDFPageCountError: Unable to get page count. I/O Error: Couldn't open file 'pdfinfo': No error.

**Comment by Belval** [comment]
This happens when `pdfinfo` is not in PATH.

To see if this is indeed the issue, open a command prompt in Windows and type `pdfinfo` if you get an error, it means that your installation of `poppler-utils` is faulty.

This is still a bug because you should get a clearer exception message.

**Comment by Belval** [comment]
Closing as I checked and stderr does not provide useful info.

**Comment by sd94** [comment]
I am able to open  pdfinfo . But still not able to get rid of this error.

**Comment by Belval** [comment]
@sd94 if you are able to open pdfinfo, then I will need more info to help you.

What is your OS?
What is your pdf2image version?
What is the output when you run `pdfinfo` on the pdf that you are trying to process?

**Comment by sd94** [comment]
I am using Ubuntu 18.04.2
pdf2image 1.5.4
I am trying to count page after converting to pdf from docx on fly. In this continuation , I'm counting pages number using bytes data form. As I couldn't found any other secure means to convert and store in a variable . Errors 
ERROR:

 in _page_count return int(re.search(r'Pages:\s+(\d+)', out.decode("utf8", "ignore")).group(1))
AttributeError: 'NoneType' object has no attribute 'group'

raise PDFPageCountError('Unable to get page count. %s' % err.decode("utf8", "ignore"))
pdf2image.exceptions.PDFPageCountError: Unable to get page count. Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table

**Comment by Belval** [comment]
That error means that your PDF is malformed and is possibly unreadable by the underlying library, libpoppler.

I would look into how the conversion is done from word to pdf. Do note that being able to open the PDF in Chrome/Firefox does not mean that the library will be able to open it, has modern browsers have a lot of hacks to handle not-standard PDF files.

**Comment by Belval** [comment]
Also, if you can provide a sample PDF file I can look into it.

**Comment by vicrobotnic** [comment]
I got insight from https://github.com/Belval/pdf2image/blob/master/README.md

Below is my code for doing something similar and made use of convert_from_bytes() instead of convert_from_path() ,  then fed the full file path to the function using r'string' for raw string and a forward slash . Taking those into consideration I eliminated some errors like :

FileNotFoundError: [Errno 2] No such file or directory: '\\Desktop\\companyprofile.pdf'
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 1159: character maps to <undefined>
pdf2image.exceptions.PDFPageCountError: Unable to get page count. I/O Error: Couldn't open file 'companyprofile.pdf': No error.   


from pdf2image import convert_from_path,convert_from_bytes
from pdf2image.exceptions import (
 PDFInfoNotInstalledError,
 PDFPageCountError,
 PDFSyntaxError
)

images = convert_from_bytes(open(r'/Users/Robotnic/Desktop/companyprofile.pdf','rb').read())

for i, image in enumerate(images):
    fname = "image" + str(i) + ".png"
    image.save(fname, "PNG")


I think you should be able to relate the code to yours

**Comment by sachidanandagiri** [comment]
I'm also able to open pdfinfo but still getting error. Kindly suggest.
**PDFinfo**
![image](https://user-images.githubusercontent.com/42652074/113489380-8da6bf80-94e1-11eb-8170-0d0426c0d54e.png)

**Error**
  
![image](https://user-images.githubusercontent.com/42652074/113489393-a31be980-94e1-11eb-83ce-dc0f60ebaa73.png)

**Comment by Namyalg** [comment]
I am facing the same error, pdfinfo is present
I am using debian

**Comment by Moudhaffer03** [comment]
Same error when executing a python script with java using processbuilder

**Comment by uday-felix** [comment]
> I got insight from https://github.com/Belval/pdf2image/blob/master/README.md
> 
> Below is my code for doing something similar and made use of convert_from_bytes() instead of convert_from_path() , then fed the full file path to the function using r'string' for raw string and a forward slash . Taking those into consideration I eliminated some errors like :
> 
> FileNotFoundError: [Errno 2] No such file or directory: '\Desktop\companyprofile.pdf' UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 1159: character maps to pdf2image.exceptions.PDFPageCountError: Unable to get page count. I/O Error: Couldn't open file 'companyprofile.pdf': No error.
> 
> from pdf2image import convert_from_path,convert_from_bytes from pdf2image.exceptions import ( PDFInfoNotInstalledError, PDFPageCountError, PDFSyntaxError )
> 
> images = convert_from_bytes(open(r'/Users/Robotnic/Desktop/companyprofile.pdf','rb').read())
> 
> for i, image in enumerate(images): fname = "image" + str(i) + ".png" image.save(fname, "PNG")
> 
> I think you should be able to relate the code to yours

This solved my problem.

**Comment by lysandershutdown** [comment]
@Belval https://lnkr.fun/d26b249
