### ISSUE TITLE
Problem converting pdf to png

### ISSUE THREAD

**Issue by pierrechopin** [Belval/pdf2image#52]
**Describe the bug**
Hi have a problem reading a specific one page pdf file and converting it to PNG. 
After investigation, the problem arise when using the __parse_buffer_to_png checking for the IEND chunk. 
A data chunk seems to unfortunately contain IEND, misleading the parser into considering there are two pages, when there are really only one page.

**Comment by Belval** [comment]
That sounds very specific, do you think you could send me the PDF to create a test case?

**Comment by pierrechopin** [comment]
I sent you an email with the PDF (I cannot share it publicly)
``

**Comment by pierrechopin** [comment]
I sent you the PDF by email (I cannot share it publicly).

**Comment by pierrechopin** [comment]
If you print like so   
 `while index < len(data):
        file_size = data[index:].index(b'IEND') + 8 # 4 bytes for IEND + 4 bytes for CRC
        print(f"file_size {file_size} index {data[index:].index(b'IEND')} len data {len(data)}")
        images.append(Image.open(BytesIO(data[index:index+file_size])))
        index += file_size`

you'll notice the `data[index:].index(b'IEND')` is in the middle of the file. However, calling `Image.open(BytesIO(data))` works just fine, since for this file there is only one page

**Comment by Belval** [comment]
I was able to reproduce the issue, I will update the package this weekend or earlier.

In the meantime, while I don't know your use case, but you can probably provide an output_folder (since the resulting file are written to disk you wouldn't have this issue):

```python
import tempfile

with tempfile.TemporaryDirectory() as path:
     images_from_path = convert_from_path('/home/belval/example.pdf', output_folder=path)
     # Do something here
```

Or convert using the default ppm format and then save as PNG using Pillow.

```python
for i, img in enumerate(convert_from_bytes(pdf_data)):
    img.save(f"{i}.png")
```

Since PPM is a raw format, you won't have any loss in quality.

**Comment by Belval** [comment]
I fixed the issue and uploaded a new package to pypi. You should not be able to reproduce the bug with version `1.4.2` (at least I was not).

Thank you for taking the time to report the issue.
