### ISSUE TITLE
Crop before generating image

### ISSUE THREAD

**Issue by matheusjardimb** [Belval/pdf2image#55]
Hello there,

Is there any way I can export a small selection of a single page to image? I mean, providing coords to get an image 'crop' from a page, instead of getting full page as image.

It may be an undocumented feature that the lib already supports. I found 'use_cropbox' but couldn't find how to provide such coords.   

The files I'm using always have some useless header and footer that I want to get rid of.

**Comment by Belval** [comment]
Unfortunately know, `cropbox` for poppler is a way to extract information from pdf files and not related to actual cropping. I'd recommend to use Pillow for this.

```
from PIL import Image
from pdf2image import convert_from_path

header_offset = 200
footer_offset = 1200 
images = [
    page.crop((0, header_offset, page.width, footer_offset))
    for page in convert_from_path('your_file.pdf')
]
```

**Comment by matheusjardimb** [comment]
Tks! I'm already doing something similar to your suggestion with PIL. 

I was wondering if using some cropping directly into pdf2image would be more efficient.
