### ISSUE TITLE
Is there a way to skip disk r/w operations, and we can directly use the image object without saving it on disk.

### ISSUE THREAD

**Issue by singhmousam** [Belval/pdf2image#58]
Currently I am working on an OCR project in which I have used pdf2image library for converting pdfs into image and the converted image is fed into tesseract OCR engine, but this whole processing is taking a long time. 
There can be a way to optimize it when we can avoid disk i/o's  i.e. directly feeding the image object from pdf2image to OCR engine without writing the image onto the disk.
Is it possible to do so, if yes then how.

**Comment by Belval** [comment]
The most optimized workflow I can think of would be to use `tesserocr` with `pdf2image` without and `output_folder` or with a ramdisk.

[Tesserocr](https://github.com/sirfz/tesserocr) is a Python/Pillow friendly library that uses libtesseract.

You can do something like this:

```
from pdf2image import convert_from_path
from tesserocr import PyTessBaseAPI

images = convert_from_path('[PDF_PATH]')

with PyTessBaseAPI() as api:
    for img in images:
        api.SetImageFile(img)
        print(api.GetUTF8Text())
```

And that will limit your io to one read from disk.

**Comment by singhmousam** [comment]
Something like this would work absolutely fine:

```
dataFile = {}
def pdf_to_text(folder):
    directoryList = os.listdir(folder)
    for pdfFile in directoryList:
        if pdfFile.endswith('.pdf'):
            pages = convert_from_path(folder+'/'+pdfFile)
            for page in pages:
                text = pytesseract.image_to_string(page, config=config)
                dataFile[pdfFile.split('/')[-1].split('.')[0]+'_'+str(pages.index(page)+1)] = text
    return dataFile
```

**Comment by Belval** [comment]
Glad you got it sorted out, but pytesseract will do at least 2 R/W operations for every image you send it:

https://github.com/madmaze/pytesseract/blob/master/src/pytesseract.py#L199

As an aside, it's GPL-license makes it ill-suited for any non-free project.
