### ISSUE TITLE
Open PDF with password

### ISSUE THREAD

**Issue by maheshk3176** [Belval/pdf2image#60]
Unable to open pdf with 2nd password

convert_from_path(sys.argv[1],userpw=sys.argv[2],dpi=300)

**Comment by Belval** [comment]
Please try to open your PDF with `pdftoppm` and see if that works first.

If you are willing to provide a test case (it can be by email) I can look into it.

**Comment by Belval** [comment]
Closing for lack of response. Feel free to reopen.
