### ISSUE TITLE
In docker container to perform PDF image, Chinese is not recognized

### ISSUE THREAD

**Issue by FindHumor** [Belval/pdf2image#62]
**Describe the bug**
In docker container to perform PDF image, Chinese is not recognized. I have tried to use docker centos 7.6.1810 and ubuntu 16.04 to identify Chinese PDFS, but they are not recognized.
This is the PDF to be identified：
[031001700111-49924029.pdf](https://github.com/Belval/pdf2image/files/3111380/031001700111-49924029.pdf)

As a result：
![1556095162 1727736](https://user-images.githubusercontent.com/49555480/56645778-eb54ef00-66b0-11e9-938f-89ca91ca460a.jpg)

The code is 
**import pdf2image
import time
import sys

if __name__ == "__main__":
    filename = sys.argv[1]
    images =pdf2image.convert_from_path(filename)
    imagename = str(time.time())+".jpg"
    images[0].save(imagename)
    print(imagename)**

Dockerfile:

**
FROM centos:python3.6.5

RUN yum -y upgrade \
    && yum install -y poppler-cpp-devel \
    && yum install -y  poppler \
    && yum install -y poppler-utils \
    && pip install pdf2image
**

Execute the command：
docker run -v /home:/home -w /home --rm  -it centos:pdf2image   python3 pdfToimage.py 031001700111-49924029.pdf

**Comment by FindHumor** [comment]
The basic image of the above Dockerfile is not Shared, so the way to create a usable docker image is as follows:
#Download the image and go into the container
docker run -it centos:7.6.1810 /bin/bash

yum install -y wget gcc automake autoconf libtool make  openssl-devel bzip2-devel expat-devel gdbm-devel readline-devel sqlite-devel

wget https://www.python.org/ftp/python/3.6.5/Python-3.6.5.tgz

tar -xzvf Python-3.6.5.tgz

cd Python-3.6.5

./configure

make

make install 

yum install -y poppler-cpp-devel poppler poppler-utils

pip3  install pdf2image

#Out of the container
exit

#Generate the images
docker commit containerid   centos:pdf2image

**Comment by Belval** [comment]
That happens when the host OS does not have Chinese fonts installed.

Please try to install those [fonts](https://help.accusoft.com/PrizmDoc/v12.2/HTML/Installing_Asian_Fonts_on_Red_Hat_and_CentOS.html) first.

**Comment by FindHumor** [comment]
Thank you very much. The problem has been solved！
