### ISSUE TITLE
when first_page exceeds last page error is thrown

### ISSUE THREAD

**Issue by vorg-san** [Belval/pdf2image#65]
when running this code:

```
pages = convert_from_path("./" + a, dpi = 200, output_folder = dir_img, fmt = 'JPEG', 
		first_page = max(existem)+1) 
```

I get the error 

```
File "/xxx/.local/lib/python3.6/site-packages/pdf2image/pdf2image.py", line 81, in convert_from_path
    reminder = page_count % thread_count
ZeroDivisionError: integer division or modulo by zero
```

the library doesn't treat the possibility of first_page being of a value greater then the number of pages of the pdf file. I was expecting for it to do nothing and return empty array.

**Comment by Belval** [comment]
Good catch, I'll see to it.

**Comment by Belval** [comment]
`first_page` greater than `last_page` returns an empty list from now on. Thank you for your report.

**Comment by vorg-san** [comment]
Thanks for the quick fix!!!
