### ISSUE TITLE
add option to suppress page-suffix

### ISSUE THREAD

**Issue by janedoesrepo** [Belval/pdf2image#71]
My Code:
`img = convert_from_path(str(pdf_path), last_page=1, fmt=fmt, output_folder=out_path, output_file=new_name)`

I only extract the first page from each document. It would be nice to have anoption to suppress the suffix that gets added to `new_name` value of `output_file`.

Example:
With `new_name = 'image_converted'` and assuming the PDF-File has 20 pages, the `output_file` will become `image_converted-01.fmt`

Is there a way to suppress "-01"?

**Comment by Belval** [comment]
This behaviour comes from `pdftoppm`/`pdftocairo`, and not from `pdf2image`. As such, I cannot fix it.

You could do something like
```
import os

img = convert_from_path(
    str(pdf_path),
    last_page=1,
    fmt=fmt,
    output_folder=out_path,
    output_file=new_name)[0]

os.rename(img.filename, os.path.join(out_path, output_file + '.' + fmt))
```

But I understand why that would be less elegant.

**Comment by Belval** [comment]
Actually, there seems to be a `-singlefile` option in `pdftoppm` that removes the digit. I suppose that could be added as a parameter.

**Comment by janedoesrepo** [comment]
That'd be really cool. And elegant ;-) Thank you!
