### ISSUE TITLE
How to get specific pages Images via pdf2image

### ISSUE THREAD

**Issue by Mahendra114027** [Belval/pdf2image#75]
Hi,

I have a pdf with 20 pages. 
I want to retrieve images of pages 1, 3, 5, 9, 17 at once. Is there any option in pdf2image to do so?

**Comment by Belval** [comment]
There is no option in `pdf2image` to do this at the present time no. You can get the desired result by calling `convert_from_path` 5 times if performance really is an issue.

```py
from pdf2image import convert_from_path

pages = []
for i in [1, 3, 5, 9, 17]:
    pages.append(convert_from_path('/home/belval/file.pdf', first_page=i, last_page=i))
```

That will call `pdfinfo` 5 times as well, but the overhead will be much less than converting 15 pages for nothing.

**Comment by Mahendra114027** [comment]
Thanks, I was also using a similar looping approach to solve this temporarily.
