### ISSUE TITLE
PIL.Image.DecompressionBombError

### ISSUE THREAD

**Issue by luckydog5** [Belval/pdf2image#76]
When i convert a pdf file(only one page, 8m), something unexpected happend.

images = convert_from_bytes(pdf_bytes.getvalue(),dpi=200)

PIL.Image.DecompressionBombError: Image size (280835475 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.

How could i fix this, please give me some advice.

My pdf file.

[中文解剖学page_21.pdf](https://github.com/Belval/pdf2image/files/3421696/page_21.pdf)

**Comment by Belval** [comment]
You can set the max pixel count for Pillow like this:

```
from PIL import Image Image.MAX_IMAGE_PIXELS = 1000000000 
```

You can just increase the number until it works.

**Comment by luckydog5** [comment]
Thank you very very much..

**Comment by dns-smitk** [comment]
> from PIL import Image Image.MAX_IMAGE_PIXELS = 1000000000

from PIL import Image; Image.MAX_IMAGE_PIXELS = 1000000000
