### ISSUE TITLE
convert_from_path() returns an empty list

### ISSUE THREAD

**Issue by S-aiueo32** [Belval/pdf2image#77]
Hi,
I use your package in [this repository](https://github.com/S-aiueo32/kill-docx) like:
```python
def save_pages(filename):
	pages = convert_from_path(str(src_dir / filename))  # here returns empty list
	out_files = []
	for i, page in enumerate(pages):
		out_file = src_dir / f'{filename.replace(".pdf", "")}_{i:0>4}.png'
		out_files.append(out_file)
		page.save(out_file)
	return out_files
```
It works well on my 2nd workstation, however doesn't work on my main workstation.
Both workstations have Windows 10 OS.
I build environments by the same way using only  `pipenv`.

Do you have any idea for this behavior?

**Comment by Belval** [comment]
Please from powershell/cmd, run `pdftoppm -r 200 -png in.pdf out` and see what it outputs.

Do this on both machines.

**Comment by S-aiueo32** [comment]
Thank you for advice.

I run the command on both machines and only main machine did not work properly.
I checked my environment variables, then I noticed that locally installed LaTeX's `pdftoppm` prevent the execution.
I fixed the order of environment variables, it started to work well. 

Thanks for this awesome work. I'll close here.
