### ISSUE TITLE
Extra space between capital letters

### ISSUE THREAD

**Issue by luckydog5** [Belval/pdf2image#81]
When I converted a pdf file to image, some extra spaces appeared between capital letters.
My os is Centos6
origin pdf
[1_0.pdf](https://github.com/Belval/pdf2image/files/3500785/1_0.pdf)

bad image

![bad](https://user-images.githubusercontent.com/35583878/63012177-5fafda00-bebc-11e9-9b87-a610baaf0f51.png)
 

bug region

![bug](https://user-images.githubusercontent.com/35583878/63012215-6f2f2300-bebc-11e9-8f11-89ef7cf24116.jpg)

**Comment by luckydog5** [comment]
There are extra space in "91110302MA01BPNU8D"

**Comment by luckydog5** [comment]
I have solved it.
My linux machine lack of the  Helvetica.ttf font, when i added it to the system, nothing goes wrong.

**Comment by Belval** [comment]
Thanks for the update, it might help people in the future.
