### ISSUE TITLE
Option to save image as Grayscale

### ISSUE THREAD

**Issue by NikhilGupta1997** [Belval/pdf2image#83]
For detailed PDFs it takes a long time to convert each page to a PNG.
It will be much faster if we save the PNG in Grayscale. 
There should be a parameter to address this use case.

**Comment by Belval** [comment]
The root of this problem can be traced to libpng, used by libpoppler to convert the PDF into images.

I think it would be worth documenting the situation, but I don't think it can be addressed from `pdf2image`.

Unless what you meant is that you want access to the `-gray` parameter, which should be addressed by the #82

**Comment by NikhilGupta1997** [comment]
Yes! The new parameter is what I was looking for.

**Comment by Belval** [comment]
Good to hear, the PR author has written any tests yet so I cannot merge it. If he has not done it by next Saturday I will do it and upload the new package.
