### ISSUE TITLE
Pathlib Path object support

### ISSUE THREAD

**Issue by Plat251** [Belval/pdf2image#87]
[Pathlib](https://docs.python.org/3/library/pathlib.html) is a standard Python library which offers more powerful and flexible support for paths than [os](https://docs.python.org/3/library/os.html) library.

While you still can use Path objects with pdf2image by casting them as Strings before passing them as arguments, I think it would be better if pdf2image supported this natively.

Worse even, if it attempts to parse a Path as its first positional argument instead of a String, it throws a PDFInfoNotInstalledError exception. I have spent an embarrassing amount of time figuring out how I botched that process. It turns out I didn't, but I did attempt to use Path objects when Strings were expected, and that broke everything.

**Comment by Belval** [comment]
#88 is now merged.
