### ISSUE TITLE
__load_from_output_folder fails on MacOS because of .DS_Store file

### ISSUE THREAD

**Issue by maephisto666** [Belval/pdf2image#9]
On MacOS, whenever we use 

- `convert_from_path`
- `convert_from_bytes`

functions, if we pass an `output_folder` they end up calling `__load_from_output_folder` function. 

If we use an existing folder, already visited with the Finder app, the function fails saying that `.DS_Store` is not a valid image.

The problem is that this file is created automatically by MacOS Finder app. My suggestion if that this can be fixed passing a list of files to be ignored. If you agree, I can make the pull request.

**Comment by Belval** [comment]
I looked into it and I'll just ignore files that start with a '.' that way any hidden file won't be processed.

**Comment by Belval** [comment]
See https://github.com/Belval/pdf2image/commit/8153911c523d5b94817130ffca39f7fe85847ab0 does this solution solve your problem?

**Comment by maephisto666** [comment]
Partly. This way we are assuming that the `output_folder` is always a fresh one. Otherwise:
- if it contains other images, they will be returned as part of the result of the current call;
- if it contains other files (e.g. pdf files) not starting with a '.', we will get the error as well.

**Comment by Belval** [comment]
Points taken, pdf2image should not expect the folder to be empty. I will fix this by having a unique identifier in every generated image so the folder will not matter as long as you have the permissions.

**Comment by Belval** [comment]
So https://github.com/Belval/pdf2image/commit/f2b5b1be783aed27ee36c4cb3af7430f9c31ff9c

It fixes your problem by exclusively considering images generated by pdftoppm in the function call you made. You can now use and reuse the same folder (without cleaning it if you want) and it will not throw.

Please tell me if that solve your problem.

**Comment by maephisto666** [comment]
Well, it helps. 
I left two comments in the commit.
