### ISSUE TITLE
How to control output image size

### ISSUE THREAD

**Issue by luckydog5** [Belval/pdf2image#93]
Sometimes when i converted a pdf file to images, each  image is more than 20MB.
How can i reduce the size of the image without change the dpi(400).
The pdf i use:
[不可编辑PDF.pdf](https://github.com/Belval/pdf2image/files/3630163/PDF.pdf)

**Comment by Belval** [comment]
Right now there is no such thing, what I would recommend is scaling with pillow afterwards:

```py
from pdf2image import convert_from_path

images = convert_from_path(dpi=400, 'your_pdf_here.pdf')

for img in images:
    img.thumbnail((max_width, max_height))
```

Pillow is quite fast so usually, it will not be an issue. I would also recommend using `fmt='jpeg'` to get a much faster conversion speed.

`pdftoppm` does have a `-scale-to` parameter (https://linux.die.net/man/1/pdftoppm). I have not implemented it yet, but if you feel like it would be beneficial to your use case, tell me, I'll implement it.

**Comment by luckydog5** [comment]
Thank you very much for your valuable comments, i will try them first.
It is very kind of you if you could implement it for me, cause in my case, image size do have a huge impact on performance.
Anyway, thank you very much 🙏.

**Comment by Belval** [comment]
Version 1.9.0 will include the `size=(width, height)` parameter.
